In [1]:
## import data manipulation packages
import pandas as pd
import numpy as np
from sklearn.neighbors import DistanceMetric
from math import radians

## import dataset "medium size" as variable 'city' and drop NaN
cities = pd.read_excel('data/medium_cities.xlsx')
ct = cities.dropna(axis = 'rows', how = 'any')
## considero solo al di sopra dell'equatore
## ct = ct[ct.lat >= 0]

In [2]:
#add london Start (spostando lievemente la longitudine, così che sia più ad est di London)
London_st = ct.loc[(ct['city'] == 'London') & (ct['iso3'] == 'GBR')]
London_st['city']='London_st' 
London_st['lng'] = London_st['lng'] + 0.2

<ipython-input-2-b81702dafba4>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  London_st['city']='London_st'
<ipython-input-2-b81702dafba4>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  London_st['lng'] = London_st['lng'] + 0.2

In [3]:
## attacco la riga London_st al dataframe
ct = ct.append(London_st)

In [4]:
## resetto l'index, che sia progressivo
ct = ct.reset_index()
print(ct)

     index                     city               city_ascii      lat  \
0        0                   London                   London  51.5072
1        8                 Qadsayyā                 Qadsayya  33.5333
2       11                 Szczecin                 Szczecin  53.4247
3       24                Stratford                Stratford -39.3410
4       25             Medzilaborce             Medzilaborce  49.2717
..     ...                      ...                      ...      ...
299   1086  San Martín de los Andes  San Martin de los Andes -40.1667
300   1090            Phanat Nikhom            Phanat Nikhom  13.4458
301   1094                   Roanne                   Roanne  46.0367
302   1098                Keszthely                Keszthely  46.7675
303      0                London_st                   London  51.5072

          lng         country iso2 iso3            admin_name  capital  \
0     -0.1275  United Kingdom   GB  GBR       London, City of  primary
1     36.2167           Syria   SY  SYR           Rīf Dimashq    minor
2     14.5553          Poland   PL  POL    Zachodniopomorskie    admin
3    174.2840     New Zealand   NZ  NZL              Taranaki    admin
4     21.9042        Slovakia   SK  SVK             Prešovský    minor
..        ...             ...  ...  ...                   ...      ...
299  -71.3500       Argentina   AR  ARG               Neuquén    minor
300  101.1844        Thailand   TH  THA             Chon Buri    minor
301    4.0689          France   FR  FRA  Auvergne-Rhône-Alpes    minor
302   17.2463         Hungary   HU  HUN                  Zala    minor
303    0.0725  United Kingdom   GB  GBR       London, City of  primary

     population          id
0    10979000.0  1826645935
1       33571.0  1760188872
2      403833.0  1616256546
3        5740.0  1554001293
4        6612.0  1703717688
..          ...         ...
299     27956.0  1032807074
300     11032.0  1764762615
301     34366.0  1250674978
302     19387.0  1348430852
303  10979000.0  1826645935

[304 rows x 12 columns]

In [5]:
## concatenate iso2 and city to get unique id
ct['ID'] = ct['city'].map(str) + ct['iso2'].map(str)

In [6]:
## drop not usable columns
ct = ct.drop(['city_ascii', 'country', 'iso2', 'admin_name', 'capital', 'id'], axis = 1)

In [7]:
## droppo la colonna index duplicata
ct = ct.drop('index', axis = 1)

In [8]:
# population - dove la popolazione è > di 200,000 abitanti aggiungo peso 2
pop = np.where(ct['population'] < 200000 , 0 , 2 )
#same state  - dove lo stato è diverso aggiungo peso 2
i = ct['iso3'].to_numpy()
st = (i[:, None ] != i) * 2

In [9]:
print(st)

[[0 2 2 ... 2 2 0]
 [2 0 2 ... 2 2 2]
 [2 2 0 ... 2 2 2]
 ...
 [2 2 2 ... 0 2 2]
 [2 2 2 ... 2 0 2]
 [0 2 2 ... 2 2 0]]

In [10]:
# direction - lavoro sulla longitudine e prendo le longitudini ad "est", normalizzando le long negative aggiungendo 150
## forse dobbiamo aggiungere 180? visto che dovrebbe essere su 360 totale?

dr_x = np.where(ct['lng'] > -180, ct['lng'] +180, ct['lng'] + 0)
x = dr_x
drdf = (x[:, None ] < x)*1

In [11]:
print(drdf)

[[0 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 ...
 [0 1 1 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]]

In [12]:
# metto i giusti indici alle matrici 
direction = pd.DataFrame(drdf, columns = ct['ID'], index = ct['ID'])
same_state = pd.DataFrame(st, columns = ct['ID'], index = ct['ID'])
population = pd.DataFrame(pop , index = ct['ID'])

In [13]:
print(direction)

ID                         LondonGB  QadsayyāSY  SzczecinPL  StratfordNZ  \
ID
LondonGB                          0           1           1            1
QadsayyāSY                        0           0           0            1
SzczecinPL                        0           1           0            1
StratfordNZ                       0           0           0            0
MedzilaborceSK                    0           1           0            1
...                             ...         ...         ...          ...
San Martín de los AndesAR         1           1           1            1
Phanat NikhomTH                   0           0           0            1
RoanneFR                          0           1           1            1
KeszthelyHU                       0           1           0            1
London_stGB                       0           1           1            1

ID                         MedzilaborceSK  SabinasMX  Parras de la FuenteMX  \
ID
LondonGB                                1          0                      0
QadsayyāSY                              0          0                      0
SzczecinPL                              1          0                      0
StratfordNZ                             0          0                      0
MedzilaborceSK                          0          0                      0
...                                   ...        ...                    ...
San Martín de los AndesAR               1          0                      0
Phanat NikhomTH                         0          0                      0
RoanneFR                                1          0                      0
KeszthelyHU                             1          0                      0
London_stGB                             1          0                      0

ID                         DevinBG  AnnabaDZ  CouvaTT  ...  SarnenCH  \
ID                                                     ...
LondonGB                         1         1        0  ...         1
QadsayyāSY                       0         0        0  ...         0
SzczecinPL                       1         0        0  ...         0
StratfordNZ                      0         0        0  ...         0
MedzilaborceSK                   1         0        0  ...         0
...                            ...       ...      ...  ...       ...
San Martín de los AndesAR        1         1        1  ...         1
Phanat NikhomTH                  0         0        0  ...         0
RoanneFR                         1         1        0  ...         1
KeszthelyHU                      1         0        0  ...         0
London_stGB                      1         1        0  ...         1

ID                         Hà GiangVN  NangandaoCN  HódmezővásárhelyHU  \
ID
LondonGB                            1            1                   1
QadsayyāSY                          1            1                   0
SzczecinPL                          1            1                   1
StratfordNZ                         0            0                   0
MedzilaborceSK                      1            1                   0
...                               ...          ...                 ...
San Martín de los AndesAR           1            1                   1
Phanat NikhomTH                     1            1                   0
RoanneFR                            1            1                   1
KeszthelyHU                         1            1                   1
London_stGB                         1            1                   1

ID                         NavolatoMX  San Martín de los AndesAR  \
ID
LondonGB                            0                          0
QadsayyāSY                          0                          0
SzczecinPL                          0                          0
StratfordNZ                         0                          0
MedzilaborceSK                      0                          0
...                               ...                        ...
San Martín de los AndesAR           0                          0
Phanat NikhomTH                     0                          0
RoanneFR                            0                          0
KeszthelyHU                         0                          0
London_stGB                         0                          0

ID                         Phanat NikhomTH  RoanneFR  KeszthelyHU  London_stGB
ID
LondonGB                                 1         1            1            1
QadsayyāSY                               1         0            0            0
SzczecinPL                               1         0            1            0
StratfordNZ                              0         0            0            0
MedzilaborceSK                           1         0            0            0
...                                    ...       ...          ...          ...
San Martín de los AndesAR                1         1            1            1
Phanat NikhomTH                          0         0            0            0
RoanneFR                                 1         0            1            0
KeszthelyHU                              1         0            0            0
London_stGB                              1         1            1            0

[304 rows x 304 columns]

In [14]:
## coversion of coordinated in degrees to radians
ct['lat'] = np.radians(ct['lat'])
ct['lng'] = np.radians(ct['lng'])

In [15]:
## get the scipy metrics
dist = DistanceMetric.get_metric('haversine')

In [16]:
## prepare the array to get in input for the distance calculation
ct[['lat','lng']].to_numpy()

array([[ 8.98970228e-01, -2.22529480e-03],
       [ 5.85266494e-01,  6.32100659e-01],
       [ 9.32436917e-01,  2.54037909e-01],
       [-6.86629981e-01,  3.04182963e+00],
       [ 8.59953393e-01,  3.82300410e-01],
       [ 4.86248730e-01, -1.76487694e+00],
       [ 4.44016998e-01, -1.78336347e+00],
       [ 7.28544063e-01,  4.25846375e-01],
       [ 6.44026494e-01,  1.35554487e-01],
       [ 1.81805712e-01, -1.07250483e+00],
       [ 2.37945973e-01,  2.87687857e-01],
       [ 8.39707574e-01,  8.96907249e-02],
       [ 7.29949053e-01, -1.24649146e+00],
       [ 8.17395285e-01,  5.14580659e-01],
       [ 1.85004901e-01,  1.81805189e+00],
       [ 2.41433141e-01,  3.63634114e-01],
       [ 1.63188285e-01,  7.47000920e-01],
       [ 3.68390136e-01, -1.32883610e+00],
       [ 2.58256369e-01, -1.56283763e+00],
       [-3.92699082e-01, -1.11410126e+00],
       [ 1.10132719e+00,  4.02540993e-01],
       [ 7.93833340e-01,  3.15904595e-01],
       [ 2.60362982e-01, -4.10312945e-01],
       [ 7.03076219e-01,  1.21504063e+00],
       [ 1.09286758e+00,  3.90953752e-01],
       [ 3.15323400e-01, -1.62606567e+00],
       [ 8.80305677e-01,  2.90646190e-01],
       [ 1.93150352e-01,  1.34390352e-01],
       [ 8.03432651e-01,  2.88560521e-01],
       [-6.15980798e-01,  2.60275541e+00],
       [ 6.35313810e-01,  8.22278716e-01],
       [ 8.74982423e-01,  1.55629264e-01],
       [ 6.94241362e-01, -1.50352785e+00],
       [ 6.48098347e-01, -1.48934181e-01],
       [ 5.73921854e-01,  6.29191195e-01],
       [ 1.91244453e-01,  1.86475515e+00],
       [ 8.32230583e-01,  2.89433186e-01],
       [ 6.41549872e-01,  1.16760607e+00],
       [ 7.69006031e-01,  2.28845303e+00],
       [ 9.22067916e-01, -1.20980988e-01],
       [ 4.83005908e-01, -1.42205937e-01],
       [ 9.29052723e-01,  1.30075898e-01],
       [ 7.59509695e-01,  2.83616003e-01],
       [ 8.98319221e-01,  1.19579488e-01],
       [ 3.56939031e-01, -1.77201359e+00],
       [ 8.11286632e-01,  7.24892834e-01],
       [ 8.26966670e-01,  2.63495848e-01],
       [ 8.69795305e-01,  3.19264353e-01],
       [ 9.37533278e-01,  1.59552241e+00],
       [ 8.56001968e-01, -2.52252437e-02],
       [ 1.02770746e+00,  4.46223094e-01],
       [ 7.81034840e-01,  3.35394686e-01],
       [ 7.33600282e-01,  4.24153405e-01],
       [ 6.11156708e-01,  2.37102979e+00],
       [ 4.58424691e-01,  2.05303429e+00],
       [ 6.92386077e-01,  1.86421061e+00],
       [-4.17133691e-01,  5.13999465e-01],
       [-3.11242820e-01,  8.45030828e-01],
       [ 6.87671943e-01,  1.17392067e+00],
       [ 9.22368112e-01,  1.40392540e-01],
       [ 4.05359700e-01,  9.86407733e-01],
       [ 8.70338102e-01,  1.50970980e-01],
       [ 2.16253276e-01, -9.54695101e-02],
       [ 6.55952329e-01, -1.50679510e-01],
       [-2.63003665e-02,  5.89994591e-01],
       [ 3.61574625e-01, -1.80467045e+00],
       [ 1.60404485e-01, -1.76627320e-01],
       [ 4.26727766e-01, -1.81728045e+00],
       [ 9.53187136e-01,  4.53005443e-01],
       [ 3.48226347e-01, -1.73717507e+00],
       [ 5.33034026e-01, -1.93941859e+00],
       [ 1.15744476e+00,  2.47255559e-01],
       [ 7.82605637e-01, -1.01229097e-02],
       [ 3.75245789e-02,  1.97513675e-01],
       [ 3.30478094e-01, -1.72613063e+00],
       [ 4.71238898e-01,  1.94080787e+00],
       [ 3.23627677e-01, -1.26254675e+00],
       [ 7.66199542e-01,  4.53204411e-01],
       [ 7.22566310e-01,  2.23722063e+00],
       [ 5.60542160e-01,  3.50229985e-01],
       [ 1.38076488e-01,  1.71648769e+00],
       [ 2.53364212e-01,  7.56019036e-01],
       [-6.28842129e-03,  7.42618398e-01],
       [ 1.35554487e-01,  7.97039510e-02],
       [ 9.10402135e-01,  1.83903598e-01],
       [ 6.26616835e-01,  6.29370964e-01],
       [-6.53987088e-01, -1.26277538e+00],
       [ 7.75444551e-01,  4.25235510e-01],
       [ 7.57609031e-01,  4.29705298e-01],
       [ 9.73122287e-01,  6.56554467e-01],
       [ 6.19427824e-01,  1.96957439e+00],
       [ 6.41408500e-01,  6.32100659e-01],
       [ 9.24476470e-01,  6.29529789e-01],
       [ 4.55822405e-01, -1.80554311e+00],
       [ 2.40687885e-01,  9.18025733e-02],
       [ 5.53473576e-01,  1.95922110e+00],
       [-6.99877030e-01, -1.12457323e+00],
       [ 4.37098513e-01, -1.83991213e+00],
       [ 2.56207353e-01,  1.76972197e+00],
       [ 7.99327636e-01,  2.64640784e-01],
       [-6.04974752e-01, -1.01871029e+00],
       [-5.72904327e-01, -1.20081620e+00],
       [ 5.28543293e-01,  9.96001808e-01],
       [ 8.60892380e-01,  4.90214118e-01],
       [ 8.51055705e-01,  1.43829093e-01],
       [ 1.99840199e-01,  1.82445026e+00],
       [ 1.00821911e+00,  7.14420859e-01],
       [ 1.36716876e-01,  6.86490355e-02],
       [ 8.67346608e-01,  3.84311029e-01],
       [ 1.02641766e+00,  4.43823266e-01],
       [ 6.76023615e-01,  7.24156305e-01],
       [ 7.86852023e-01,  2.46382895e-01],
       [ 8.33103248e-01,  1.80060383e-01],
       [ 2.48765269e-01,  2.28826628e-01],
       [ 8.87499925e-01,  5.03230783e-02],
       [-4.43662696e-03, -1.38181033e+00],
       [ 8.33394718e-01, -5.86430629e-02],
       [ 5.78150787e-01,  6.25245006e-01],
       [ 8.67215708e-01,  6.34528412e-01],
       [ 8.78773278e-01,  1.94895682e-01],
       [ 3.28919515e-01, -1.69148410e+00],
       [ 1.09233351e+00,  4.12236297e-01],
       [ 3.61283155e-01, -1.74213006e+00],
       [ 6.79805744e-01,  3.62155820e-01],
       [ 5.10768860e-01,  1.55124689e+00],
       [ 4.82932604e-02,  7.94414534e-01],
       [ 8.78965265e-01,  5.80587266e-01],
       [ 1.85586095e-01, -1.07134069e+00],
       [-5.02363355e-01,  4.92764044e-01],
       [ 9.18043187e-01,  2.15256693e-01],
       [ 9.16716736e-01,  1.06412724e-01],
       [ 3.83680965e-01, -1.72816743e+00],
       [ 1.03615136e+00,  2.35617704e-01],
       [ 1.34913951e-01,  1.48876585e-01],
       [ 3.84302303e-01, -1.37362823e+00],
       [ 6.25395104e-01, -1.37258801e+00],
       [ 7.93543615e-01,  6.88532390e-01],
       [ 8.41709466e-01,  2.21236191e-01],
       [ 1.91288086e-01, -1.30550628e+00],
       [ 4.27605667e-02,  5.49778714e-01],
       [-4.73842929e-01, -1.90995394e+00],
       [ 5.38215908e-01,  6.21410518e-01],
       [ 4.94509373e-01, -1.75987308e+00],
       [ 2.99477556e-01, -1.55455778e+00],
       [ 3.22304717e-01, -1.35990296e+00],
       [ 5.37219325e-01,  1.85231794e+00],
       [ 3.47611991e-01, -1.72205878e+00],
       [ 7.77786783e-01,  4.77628548e-01],
       [ 1.23743844e-01, -1.28892565e+00],
       [ 8.15766892e-01,  3.73112997e-01],
       [ 6.13875931e-01,  5.82329105e-01],
       [-6.25620252e-01, -1.24961909e+00],
       [-3.12002038e-01,  6.43803092e-01],
       [ 6.95004071e-01,  6.07519442e-01],
       [ 7.47292390e-01, -2.87979327e-02],
       [-6.51299281e-01, -1.03207078e+00],
       [ 1.06756031e+00,  4.16576931e-01],
       [ 9.61159800e-01,  1.85296371e-01],
       [ 2.54957697e-02,  5.92296680e-01],
       [ 7.53900206e-01,  4.06413879e-01],
       [ 3.22302972e-01, -1.24645481e+00],
       [-8.42924216e-02,  2.94958898e-01],
       [ 6.73313119e-02,  2.01028769e-01],
       [ 9.88428825e-01,  8.35939408e-01],
       [ 3.93280276e-01,  1.97833071e+00],
       [ 3.97207267e-01,  2.11436865e+00],
       [ 5.74794519e-01,  2.10893370e-01],
       [ 8.62972813e-01,  1.35592884e-01],
       [ 9.56140233e-01,  5.59295995e-01],
       [ 7.47472159e-01,  1.63214465e+00],
       [ 6.12004938e-01,  6.34289302e-01],
       [ 7.85995066e-01,  4.06220147e-01],
       [ 5.27120850e-01,  2.00769762e+00],
       [ 9.40770864e-01,  4.81044158e-01],
       [-4.41568301e-02, -7.73229728e-01],
       [ 7.31172529e-01,  2.17865960e-01],
       [ 8.44564825e-01, -7.83652834e-02],
       [ 8.89826449e-01,  1.97513675e-01],
       [-5.75216888e-01, -1.05835719e+00],
       [ 1.22183520e-01,  3.34768113e-01],
       [ 6.97890845e-01, -1.44836148e+00],
       [ 4.74729557e-01,  9.81747704e-01],
       [ 9.89175826e-01,  3.84258669e-01],
       [ 1.62664686e-01,  7.35656280e-01],
       [ 8.11845138e-01,  5.17718761e-01],
       [-2.41146907e-01,  5.74213324e-01],
       [ 8.59574657e-01,  4.16261027e-01],
       [ 9.07361772e-01,  1.03375852e-01],
       [ 7.77954334e-01,  2.25815062e+00],
       [ 3.33773275e-01, -1.72380062e+00],
       [-5.87599999e-02,  6.40244365e-01],
       [ 2.82345404e-01,  1.80293908e+00],
       [ 9.02282863e-01,  3.04310372e-01],
       [ 9.25315974e-01,  4.80838209e-01],
       [ 7.12357880e-01,  1.94888526e+00],
       [ 3.72268257e-01, -2.75493241e+00],
       [ 6.31097095e-01,  6.58058941e-01],
       [ 8.39794840e-01,  2.59472864e-01],
       [ 6.14013812e-01,  1.54112573e-01],
       [ 5.37735943e-01,  1.28211363e+00],
       [ 9.99108494e-01,  3.94250679e-01],
       [ 3.91070690e-01, -1.39544484e+00],
       [ 2.75117995e-01, -1.51489343e+00],
       [ 4.46198659e-01,  9.69587995e-01],
       [ 8.72373156e-01,  1.60686705e+00],
       [ 3.06596754e-01, -1.73485728e+00],
       [ 8.39794840e-01,  6.60315652e-01],
       [ 9.89109503e-01,  2.24372547e-01],
       [ 8.92772564e-01,  2.06119894e-01],
       [ 8.26912565e-01,  1.49051118e-01],
       [ 8.02559986e-01,  8.23219448e-02],
       [ 9.86227964e-01,  4.77012447e-01],
       [ 8.54769765e-01,  2.52631173e-01],
       [ 8.05401382e-01,  2.63220086e-01],
       [-5.48324855e-01, -1.06348671e+00],
       [ 6.91567517e-01,  3.47694022e-01],
       [ 6.25351471e-01,  1.85441233e-01],
       [-1.43029732e-01,  1.99612608e+00],
       [ 7.03536985e-01,  6.37991145e-01],
       [ 9.06766614e-01,  1.39509403e-01],
       [-5.96321410e-01, -1.02829040e+00],
       [ 5.30346218e-01,  1.86358578e+00],
       [ 6.14937091e-01,  2.01469115e+00],
       [ 8.43866693e-01,  3.32780183e-01],
       [ 5.20689312e-01, -1.87564775e+00],
       [ 9.12269637e-01,  1.83627836e-01],
       [ 7.46070659e-01,  3.62829517e-01],
       [ 7.69981670e-01,  2.65581516e-01],
       [ 6.72412529e-01,  1.19621551e+00],
       [ 3.44993997e-01, -1.82154254e+00],
       [ 8.86335790e-01,  2.12086651e+00],
       [ 1.07664998e+00,  4.76014119e-01],
       [ 6.49553952e-01, -1.30027029e-01],
       [-3.15129668e-01, -1.22606413e+00],
       [ 8.61873255e-01,  5.80077630e-02],
       [ 1.36388754e-01, -1.26437062e+00],
       [ 9.11643064e-01,  3.38012680e-01],
       [ 6.71515430e-01,  8.21357182e-01],
       [ 7.04690648e-01,  1.23596538e+00],
       [ 6.05075981e-01,  6.32851151e-01],
       [ 8.32642481e-01,  1.86661916e+00],
       [ 9.72584726e-01,  4.25230274e-01],
       [ 6.96313068e-01,  1.15655290e+00],
       [ 5.90095820e-01,  5.02654825e-02],
       [ 9.27061303e-01,  4.04335192e-01],
       [ 5.46579526e-01,  7.90342681e-01],
       [ 2.42818932e-01,  1.75401750e+00],
       [ 8.31576085e-01,  1.60191555e-01],
       [ 9.20369710e-01,  2.66162711e-01],
       [ 9.15280330e-01,  5.40760598e-01],
       [ 7.63955048e-01,  1.96422845e-01],
       [-6.94888879e-01, -1.27838212e+00],
       [ 1.45473193e-01,  1.40343321e+00],
       [ 7.24747972e-01,  3.58267226e-01],
       [ 5.75958653e-01,  1.82678377e-01],
       [ 3.17112362e-01, -1.62350003e+00],
       [ 8.24736139e-01,  2.95576745e-01],
       [ 7.46128255e-02,  3.66519143e-01],
       [ 3.58083967e-01, -2.27765467e-01],
       [ 5.35234886e-01,  9.00298424e-01],
       [-6.51583770e-02, -1.27845368e+00],
       [ 7.68260775e-01,  2.36631740e-02],
       [-6.52456434e-01, -1.22638352e+00],
       [ 1.82765643e-01, -1.16135256e+00],
       [ 4.92764044e-01,  5.86722099e-01],
       [ 3.48498618e-01, -1.71945998e+00],
       [ 9.06174948e-01,  7.81907505e-02],
       [ 2.44126184e-01,  1.79245314e-01],
       [ 8.34546635e-01,  2.83616003e-01],
       [ 3.36000316e-01, -1.70857611e+00],
       [ 4.20332880e-01, -1.84888487e+00],
       [ 8.82555407e-01,  2.15926375e+00],
       [ 1.03636255e+00,  4.92193321e-01],
       [ 3.36174849e-01, -1.74991598e+00],
       [ 7.26721939e-01,  3.92077744e-01],
       [-1.54257435e-01,  2.30983855e-01],
       [ 7.59218225e-01,  3.27830429e-01],
       [ 7.62127688e-01,  3.31225095e-01],
       [ 8.59574657e-01,  5.25344105e-01],
       [ 6.70002229e-01,  1.20994950e+00],
       [ 8.91896409e-01,  1.00977769e-01],
       [ 8.82787536e-01,  2.26931200e-01],
       [ 1.75018127e-01, -1.46963879e+00],
       [ 1.10905900e+00,  5.08472007e-01],
       [ 1.82678377e-01, -1.18711536e+00],
       [ 5.23371883e-01,  5.44748675e-01],
       [ 7.43491063e-01, -9.71607341e-02],
       [ 2.01068911e-01,  1.27758101e-01],
       [ 5.43088867e-01,  1.29939763e+00],
       [-6.34078117e-01, -1.00688045e+00],
       [ 2.36509567e-01, -2.57732771e-01],
       [ 2.21075620e-01,  1.88582826e+00],
       [ 8.45030828e-01,  2.72562833e-01],
       [ 2.43181961e-01,  2.12261184e+00],
       [ 8.18505314e-01,  1.43935558e-01],
       [ 3.98341731e-01,  1.83230948e+00],
       [ 6.16087263e-01,  1.98766996e+00],
       [ 8.10361608e-01,  3.54631705e-01],
       [ 4.32241261e-01, -1.87975277e+00],
       [-7.01041165e-01, -1.24529242e+00],
       [ 2.34673481e-01,  1.76600093e+00],
       [ 8.03491992e-01,  7.10157019e-02],
       [ 8.16246858e-01,  3.01004719e-01],
       [ 8.98970228e-01,  1.26536371e-03]])

In [17]:
## pass pairwise function to get the distance / multiply for 6373 as earth sperical radius is 6373kms
dist.pairwise(ct [['lat','lng']].to_numpy())*6373

array([[   0.        , 3532.53108603, 1015.62748887, ...,  681.54793619,
        1365.60252073,   13.84624764],
       [3532.53108603,    0.        , 2796.46363452, ..., 3051.2012908 ,
        2172.98302225, 3519.54520478],
       [1015.62748887, 2796.46363452,    0.        , ..., 1112.97667748,
         764.82369326, 1002.45217865],
       ...,
       [ 681.54793619, 3051.2012908 , 1112.97667748, ...,    0.        ,
        1012.81709679,  675.08460056],
       [1365.60252073, 2172.98302225,  764.82369326, ..., 1012.81709679,
           0.        , 1352.29488838],
       [  13.84624764, 3519.54520478, 1002.45217865, ...,  675.08460056,
        1352.29488838,    0.        ]])

In [18]:
## create the distance matrix with cities in the indexes
distance = pd.DataFrame(dist.pairwise(ct[['lat','lng']].to_numpy())*6373, columns = ct['ID'], index = ct['ID'])

In [19]:
## identify 'London' ID arrival (se dovesse servire come indice)
ct.loc[(ct['city'] == 'London') & (ct['iso3'] == 'GBR')]

     city      lat       lng iso3  population        ID
0  London  0.89897 -0.002225  GBR  10979000.0  LondonGB

In [20]:
## identify 'London_st' ID start (se dovesse servire come indice)
ct.loc[(ct['city'] == 'London_st')]

          city      lat       lng iso3  population           ID
303  London_st  0.89897  0.001265  GBR  10979000.0  London_stGB

In [21]:
## get starting line from distance matrix
distance.loc[['London_stGB']]

ID,LondonGB,QadsayyāSY,SzczecinPL,StratfordNZ,MedzilaborceSK,SabinasMX,Parras de la FuenteMX,DevinBG,AnnabaDZ,CouvaTT,...,SarnenCH,Hà GiangVN,NangandaoCN,HódmezővásárhelyHU,NavolatoMX,San Martín de los AndesAR,Phanat NikhomTH,RoanneFR,KeszthelyHU,London_stGB
ID,,,,,,,,,,,,,,,,,,,,,
London_stGB,13.846248,3519.545205,1002.452179,18595.803315,1562.028155,8341.386815,8617.009881,2137.517369,1734.387158,7153.913534,...,783.969838,9012.57419,8418.932515,1576.203015,9016.659957,12312.040183,9594.060777,675.084601,1352.294888,0.0

In [22]:
from pandas import DataFrame

In [23]:
#create the graph 
graph = pd.DataFrame(np.zeros(shape=(len(ct),len(ct))) , columns = ct['ID'], index = ct['ID'])

## azzero tutti le combinazioni che non siano verso ovest
for i in distance :
    graph[i] = distance[i]*direction[i]
    
print(graph)

ID                             LondonGB    QadsayyāSY    SzczecinPL  \
ID
LondonGB                       0.000000   3532.531086   1015.627489
QadsayyāSY                     0.000000      0.000000      0.000000
SzczecinPL                     0.000000   2796.463635      0.000000
StratfordNZ                    0.000000      0.000000      0.000000
MedzilaborceSK                 0.000000   2111.200743      0.000000
...                                 ...           ...           ...
San Martín de los AndesAR  12301.328866  13711.201274  13241.231609
Phanat NikhomTH                0.000000      0.000000      0.000000
RoanneFR                       0.000000   3051.201291   1112.976677
KeszthelyHU                    0.000000   2172.983022      0.000000
London_stGB                    0.000000   3519.545205   1002.452179

ID                          StratfordNZ  MedzilaborceSK  SabinasMX  \
ID
LondonGB                   18600.596154     1575.873913        0.0
QadsayyāSY                 16248.106884        0.000000        0.0
SzczecinPL                 17828.766595      687.878762        0.0
StratfordNZ                    0.000000        0.000000        0.0
MedzilaborceSK             17579.891466        0.000000        0.0
...                                 ...             ...        ...
San Martín de los AndesAR   8953.849183    13474.171760        0.0
Phanat NikhomTH             9556.147086        0.000000        0.0
RoanneFR                   18929.870160     1380.256828        0.0
KeszthelyHU                17990.138542      444.467240        0.0
London_stGB                18595.803315     1562.028155        0.0

ID                         Parras de la FuenteMX       DevinBG      AnnabaDZ  \
ID
LondonGB                                     0.0   2150.459488   1739.964805
QadsayyāSY                                   0.0      0.000000      0.000000
SzczecinPL                                   0.0   1491.470696      0.000000
StratfordNZ                                  0.0      0.000000      0.000000
MedzilaborceSK                               0.0    859.626955      0.000000
...                                          ...           ...           ...
San Martín de los AndesAR                    0.0  13249.091792  11765.589527
Phanat NikhomTH                              0.0      0.000000      0.000000
RoanneFR                                     0.0   1692.895426   1061.654843
KeszthelyHU                                  0.0    797.576348      0.000000
London_stGB                                  0.0   2137.517369   1734.387158

ID                             CouvaTT  ...      SarnenCH    Hà GiangVN  \
ID                                      ...
LondonGB                      0.000000  ...    794.989530   9025.051667
QadsayyāSY                    0.000000  ...      0.000000   6728.629571
SzczecinPL                    0.000000  ...      0.000000   8019.384828
StratfordNZ                   0.000000  ...      0.000000      0.000000
MedzilaborceSK                0.000000  ...      0.000000   7619.857716
...                                ...  ...           ...           ...
San Martín de los AndesAR  5718.165113  ...  12471.804316  18061.681995
Phanat NikhomTH               0.000000  ...      0.000000   1117.481571
RoanneFR                      0.000000  ...    334.032389   8999.226599
KeszthelyHU                   0.000000  ...      0.000000   8018.475596
London_stGB                   0.000000  ...    783.969838   9012.574190

ID                          NangandaoCN  HódmezővásárhelyHU  NavolatoMX  \
ID
LondonGB                    8429.591631         1589.700410         0.0
QadsayyāSY                  6932.022384            0.000000         0.0
SzczecinPL                  7490.560611          879.995428         0.0
StratfordNZ                    0.000000            0.000000         0.0
MedzilaborceSK              7251.905757            0.000000         0.0
...                                 ...                 ...         ...
San Martín de los AndesAR  19310.879750        13220.807974         0.0
Phanat NikhomTH             2744.188842            0.000000         0.0
RoanneFR                    8571.854441         1248.839739         0.0
KeszthelyHU                 7688.435422          237.787387         0.0
London_stGB                 8418.932515         1576.203015         0.0

ID                         San Martín de los AndesAR  Phanat NikhomTH  \
ID
LondonGB                                         0.0      9607.297872
QadsayyāSY                                       0.0      6881.671334
SzczecinPL                                       0.0      8591.754993
StratfordNZ                                      0.0         0.000000
MedzilaborceSK                                   0.0      8107.269985
...                                              ...              ...
San Martín de los AndesAR                        0.0     16961.118781
Phanat NikhomTH                                  0.0         0.000000
RoanneFR                                         0.0      9476.416246
KeszthelyHU                                      0.0      8467.633042
London_stGB                                      0.0      9594.060777

ID                             RoanneFR   KeszthelyHU   London_stGB
ID
LondonGB                     681.547936   1365.602521     13.846248
QadsayyāSY                     0.000000      0.000000      0.000000
SzczecinPL                     0.000000    764.823693      0.000000
StratfordNZ                    0.000000      0.000000      0.000000
MedzilaborceSK                 0.000000      0.000000      0.000000
...                                 ...           ...           ...
San Martín de los AndesAR  12158.816541  13036.308524  12312.040183
Phanat NikhomTH                0.000000      0.000000      0.000000
RoanneFR                       0.000000   1012.817097      0.000000
KeszthelyHU                    0.000000      0.000000      0.000000
London_stGB                  675.084601   1352.294888      0.000000

[304 rows x 304 columns]

In [24]:
## forzo "LondonGB" ad ovest di "London_stGB" - questo andrà risolto
graph.loc['London_stGB']['LondonGB'] = 0
print(graph)

ID                             LondonGB    QadsayyāSY    SzczecinPL  \
ID
LondonGB                       0.000000   3532.531086   1015.627489
QadsayyāSY                     0.000000      0.000000      0.000000
SzczecinPL                     0.000000   2796.463635      0.000000
StratfordNZ                    0.000000      0.000000      0.000000
MedzilaborceSK                 0.000000   2111.200743      0.000000
...                                 ...           ...           ...
San Martín de los AndesAR  12301.328866  13711.201274  13241.231609
Phanat NikhomTH                0.000000      0.000000      0.000000
RoanneFR                       0.000000   3051.201291   1112.976677
KeszthelyHU                    0.000000   2172.983022      0.000000
London_stGB                    0.000000   3519.545205   1002.452179

ID                          StratfordNZ  MedzilaborceSK  SabinasMX  \
ID
LondonGB                   18600.596154     1575.873913        0.0
QadsayyāSY                 16248.106884        0.000000        0.0
SzczecinPL                 17828.766595      687.878762        0.0
StratfordNZ                    0.000000        0.000000        0.0
MedzilaborceSK             17579.891466        0.000000        0.0
...                                 ...             ...        ...
San Martín de los AndesAR   8953.849183    13474.171760        0.0
Phanat NikhomTH             9556.147086        0.000000        0.0
RoanneFR                   18929.870160     1380.256828        0.0
KeszthelyHU                17990.138542      444.467240        0.0
London_stGB                18595.803315     1562.028155        0.0

ID                         Parras de la FuenteMX       DevinBG      AnnabaDZ  \
ID
LondonGB                                     0.0   2150.459488   1739.964805
QadsayyāSY                                   0.0      0.000000      0.000000
SzczecinPL                                   0.0   1491.470696      0.000000
StratfordNZ                                  0.0      0.000000      0.000000
MedzilaborceSK                               0.0    859.626955      0.000000
...                                          ...           ...           ...
San Martín de los AndesAR                    0.0  13249.091792  11765.589527
Phanat NikhomTH                              0.0      0.000000      0.000000
RoanneFR                                     0.0   1692.895426   1061.654843
KeszthelyHU                                  0.0    797.576348      0.000000
London_stGB                                  0.0   2137.517369   1734.387158

ID                             CouvaTT  ...      SarnenCH    Hà GiangVN  \
ID                                      ...
LondonGB                      0.000000  ...    794.989530   9025.051667
QadsayyāSY                    0.000000  ...      0.000000   6728.629571
SzczecinPL                    0.000000  ...      0.000000   8019.384828
StratfordNZ                   0.000000  ...      0.000000      0.000000
MedzilaborceSK                0.000000  ...      0.000000   7619.857716
...                                ...  ...           ...           ...
San Martín de los AndesAR  5718.165113  ...  12471.804316  18061.681995
Phanat NikhomTH               0.000000  ...      0.000000   1117.481571
RoanneFR                      0.000000  ...    334.032389   8999.226599
KeszthelyHU                   0.000000  ...      0.000000   8018.475596
London_stGB                   0.000000  ...    783.969838   9012.574190

ID                          NangandaoCN  HódmezővásárhelyHU  NavolatoMX  \
ID
LondonGB                    8429.591631         1589.700410         0.0
QadsayyāSY                  6932.022384            0.000000         0.0
SzczecinPL                  7490.560611          879.995428         0.0
StratfordNZ                    0.000000            0.000000         0.0
MedzilaborceSK              7251.905757            0.000000         0.0
...                                 ...                 ...         ...
San Martín de los AndesAR  19310.879750        13220.807974         0.0
Phanat NikhomTH             2744.188842            0.000000         0.0
RoanneFR                    8571.854441         1248.839739         0.0
KeszthelyHU                 7688.435422          237.787387         0.0
London_stGB                 8418.932515         1576.203015         0.0

ID                         San Martín de los AndesAR  Phanat NikhomTH  \
ID
LondonGB                                         0.0      9607.297872
QadsayyāSY                                       0.0      6881.671334
SzczecinPL                                       0.0      8591.754993
StratfordNZ                                      0.0         0.000000
MedzilaborceSK                                   0.0      8107.269985
...                                              ...              ...
San Martín de los AndesAR                        0.0     16961.118781
Phanat NikhomTH                                  0.0         0.000000
RoanneFR                                         0.0      9476.416246
KeszthelyHU                                      0.0      8467.633042
London_stGB                                      0.0      9594.060777

ID                             RoanneFR   KeszthelyHU   London_stGB
ID
LondonGB                     681.547936   1365.602521     13.846248
QadsayyāSY                     0.000000      0.000000      0.000000
SzczecinPL                     0.000000    764.823693      0.000000
StratfordNZ                    0.000000      0.000000      0.000000
MedzilaborceSK                 0.000000      0.000000      0.000000
...                                 ...           ...           ...
San Martín de los AndesAR  12158.816541  13036.308524  12312.040183
Phanat NikhomTH                0.000000      0.000000      0.000000
RoanneFR                       0.000000   1012.817097      0.000000
KeszthelyHU                    0.000000      0.000000      0.000000
London_stGB                  675.084601   1352.294888      0.000000

[304 rows x 304 columns]

In [25]:
## traspongo per lavorare sulle righe
graph = graph.T
print(graph)

ID                             LondonGB    QadsayyāSY    SzczecinPL  \
ID
LondonGB                       0.000000      0.000000      0.000000
QadsayyāSY                  3532.531086      0.000000   2796.463635
SzczecinPL                  1015.627489      0.000000      0.000000
StratfordNZ                18600.596154  16248.106884  17828.766595
MedzilaborceSK              1575.873913      0.000000    687.878762
...                                 ...           ...           ...
San Martín de los AndesAR      0.000000      0.000000      0.000000
Phanat NikhomTH             9607.297872   6881.671334   8591.754993
RoanneFR                     681.547936      0.000000      0.000000
KeszthelyHU                 1365.602521      0.000000    764.823693
London_stGB                   13.846248      0.000000      0.000000

ID                         StratfordNZ  MedzilaborceSK     SabinasMX  \
ID
LondonGB                           0.0        0.000000   8328.946686
QadsayyāSY                         0.0     2111.200743  11844.282345
SzczecinPL                         0.0        0.000000   9070.221973
StratfordNZ                        0.0    17579.891466  11501.846804
MedzilaborceSK                     0.0        0.000000   9757.239935
...                                ...             ...           ...
San Martín de los AndesAR          0.0        0.000000   8168.761492
Phanat NikhomTH                    0.0     8107.269985  14836.091950
RoanneFR                           0.0        0.000000   8885.982100
KeszthelyHU                        0.0        0.000000   9674.255574
London_stGB                        0.0        0.000000   8341.386815

ID                         Parras de la FuenteMX       DevinBG      AnnabaDZ  \
ID
LondonGB                             8604.485457      0.000000      0.000000
QadsayyāSY                          12123.966680   1382.258306   2602.494704
SzczecinPL                           9353.677882      0.000000   1911.470935
StratfordNZ                         11253.018483  17474.928199  18811.975106
MedzilaborceSK                      10040.358348      0.000000   1786.294799
...                                          ...           ...           ...
San Martín de los AndesAR            7965.156469      0.000000      0.000000
Phanat NikhomTH                     15009.501352   7930.055793   9415.559394
RoanneFR                             9155.425883      0.000000      0.000000
KeszthelyHU                          9952.740785      0.000000   1347.597231
London_stGB                          8617.009881      0.000000      0.000000

ID                              CouvaTT  ...      SarnenCH   Hà GiangVN  \
ID                                       ...
LondonGB                    7140.636852  ...      0.000000     0.000000
QadsayyāSY                 10071.179879  ...   2779.469921     0.000000
SzczecinPL                  8156.023240  ...    853.223078     0.000000
StratfordNZ                13667.963294  ...  18613.614684  9972.017153
MedzilaborceSK              8653.948509  ...   1047.005989     0.000000
...                                 ...  ...           ...          ...
San Martín de los AndesAR      0.000000  ...      0.000000     0.000000
Phanat NikhomTH            16747.382327  ...   9143.095700     0.000000
RoanneFR                    7296.913102  ...      0.000000     0.000000
KeszthelyHU                 8309.499579  ...    684.598492     0.000000
London_stGB                 7153.913534  ...      0.000000     0.000000

ID                          NangandaoCN  HódmezővásárhelyHU    NavolatoMX  \
ID
LondonGB                       0.000000            0.000000   9004.531603
QadsayyāSY                     0.000000         1965.895681  12496.924111
SzczecinPL                     0.000000            0.000000   9707.021719
StratfordNZ                10358.388895        17770.324696  10775.501600
MedzilaborceSK                 0.000000          337.453298  10394.870252
...                                 ...                 ...           ...
San Martín de los AndesAR      0.000000            0.000000   8144.550858
Phanat NikhomTH                0.000000         8235.947917  14740.229715
RoanneFR                       0.000000            0.000000   9578.718542
KeszthelyHU                    0.000000            0.000000  10336.333069
London_stGB                    0.000000            0.000000   9016.659957

ID                         San Martín de los AndesAR  Phanat NikhomTH  \
ID
LondonGB                                12301.328866         0.000000
QadsayyāSY                              13711.201274         0.000000
SzczecinPL                              13241.231609         0.000000
StratfordNZ                              8953.849183      9556.147086
MedzilaborceSK                          13474.171760         0.000000
...                                              ...              ...
San Martín de los AndesAR                   0.000000         0.000000
Phanat NikhomTH                         16961.118781         0.000000
RoanneFR                                12158.816541         0.000000
KeszthelyHU                             13036.308524         0.000000
London_stGB                             12312.040183         0.000000

ID                             RoanneFR   KeszthelyHU   London_stGB
ID
LondonGB                       0.000000      0.000000      0.000000
QadsayyāSY                  3051.201291   2172.983022   3519.545205
SzczecinPL                  1112.976677      0.000000   1002.452179
StratfordNZ                18929.870160  17990.138542  18595.803315
MedzilaborceSK              1380.256828    444.467240   1562.028155
...                                 ...           ...           ...
San Martín de los AndesAR      0.000000      0.000000      0.000000
Phanat NikhomTH             9476.416246   8467.633042   9594.060777
RoanneFR                       0.000000      0.000000    675.084601
KeszthelyHU                 1012.817097      0.000000   1352.294888
London_stGB                    0.000000      0.000000      0.000000

[304 rows x 304 columns]

In [26]:
dis = graph.replace(0, 0)
dis

ID,LondonGB,QadsayyāSY,SzczecinPL,StratfordNZ,MedzilaborceSK,SabinasMX,Parras de la FuenteMX,DevinBG,AnnabaDZ,CouvaTT,...,SarnenCH,Hà GiangVN,NangandaoCN,HódmezővásárhelyHU,NavolatoMX,San Martín de los AndesAR,Phanat NikhomTH,RoanneFR,KeszthelyHU,London_stGB
ID,,,,,,,,,,,,,,,,,,,,,
LondonGB,0.000000,0.000000,0.000000,0.0,0.000000,8328.946686,8604.485457,0.000000,0.000000,7140.636852,...,0.000000,0.000000,0.000000,0.000000,9004.531603,12301.328866,0.000000,0.000000,0.000000,0.000000
QadsayyāSY,3532.531086,0.000000,2796.463635,0.0,2111.200743,11844.282345,12123.966680,1382.258306,2602.494704,10071.179879,...,2779.469921,0.000000,0.000000,1965.895681,12496.924111,13711.201274,0.000000,3051.201291,2172.983022,3519.545205
SzczecinPL,1015.627489,0.000000,0.000000,0.0,0.000000,9070.221973,9353.677882,0.000000,1911.470935,8156.023240,...,853.223078,0.000000,0.000000,0.000000,9707.021719,13241.231609,0.000000,1112.976677,0.000000,1002.452179
StratfordNZ,18600.596154,16248.106884,17828.766595,0.0,17579.891466,11501.846804,11253.018483,17474.928199,18811.975106,13667.963294,...,18613.614684,9972.017153,10358.388895,17770.324696,10775.501600,8953.849183,9556.147086,18929.870160,17990.138542,18595.803315
MedzilaborceSK,1575.873913,0.000000,687.878762,0.0,0.000000,9757.239935,10040.358348,0.000000,1786.294799,8653.948509,...,1047.005989,0.000000,0.000000,337.453298,10394.870252,13474.171760,0.000000,1380.256828,444.467240,1562.028155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
San Martín de los AndesAR,0.000000,0.000000,0.000000,0.0,0.000000,8168.761492,7965.156469,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,8144.550858,0.000000,0.000000,0.000000,0.000000,0.000000
Phanat NikhomTH,9607.297872,6881.671334,8591.754993,0.0,8107.269985,14836.091950,15009.501352,7930.055793,9415.559394,16747.382327,...,9143.095700,0.000000,0.000000,8235.947917,14740.229715,16961.118781,0.000000,9476.416246,8467.633042,9594.060777
RoanneFR,681.547936,0.000000,0.000000,0.0,0.000000,8885.982100,9155.425883,0.000000,0.000000,7296.913102,...,0.000000,0.000000,0.000000,0.000000,9578.718542,12158.816541,0.000000,0.000000,0.000000,675.084601
KeszthelyHU,1365.602521,0.000000,764.823693,0.0,0.000000,9674.255574,9952.740785,0.000000,1347.597231,8309.499579,...,684.598492,0.000000,0.000000,0.000000,10336.333069,13036.308524,0.000000,1012.817097,0.000000,1352.294888
London_stGB,13.846248,0.000000,0.000000,0.0,0.000000,8341.386815,8617.009881,0.000000,0.000000,7153.913534,...,0.000000,0.000000,0.000000,0.000000,9016.659957,12312.040183,0.000000,0.000000,0.000000,0.000000

In [27]:
## popolare per criteri (più vicino +2, secondo più vicino +4, terzo più vicino +8, il resto 'no go')
dis = graph.replace(0, 0)

In [28]:
dis = dis.replace(dis.apply(lambda x: x[x > 0].min(axis=0)), 2)
dis = dis.replace(dis.apply(lambda x: x[x > 2].min(axis=0)), 4)
dis = dis.replace(dis.apply(lambda x: x[x > 4].min(axis=0)), 8)

dis
#dis = dis.replace(dis.apply(lambda x: x[x > 8]), 'no go')

ID,LondonGB,QadsayyāSY,SzczecinPL,StratfordNZ,MedzilaborceSK,SabinasMX,Parras de la FuenteMX,DevinBG,AnnabaDZ,CouvaTT,...,SarnenCH,Hà GiangVN,NangandaoCN,HódmezővásárhelyHU,NavolatoMX,San Martín de los AndesAR,Phanat NikhomTH,RoanneFR,KeszthelyHU,London_stGB
ID,,,,,,,,,,,,,,,,,,,,,
LondonGB,0.000000,0.000000,0.000000,0.0,0.000000,8328.946686,8604.485457,0.000000,0.000000,7140.636852,...,0.000000,0.000000,0.000000,0.000000,9004.531603,12301.328866,0.000000,0.000000,0.000000,0.000000
QadsayyāSY,3532.531086,0.000000,2796.463635,0.0,2111.200743,11844.282345,12123.966680,1382.258306,2602.494704,10071.179879,...,2779.469921,0.000000,0.000000,1965.895681,12496.924111,13711.201274,0.000000,3051.201291,2172.983022,3519.545205
SzczecinPL,1015.627489,0.000000,0.000000,0.0,0.000000,9070.221973,9353.677882,0.000000,1911.470935,8156.023240,...,853.223078,0.000000,0.000000,0.000000,9707.021719,13241.231609,0.000000,1112.976677,0.000000,1002.452179
StratfordNZ,18600.596154,16248.106884,17828.766595,0.0,17579.891466,11501.846804,11253.018483,17474.928199,18811.975106,13667.963294,...,18613.614684,9972.017153,10358.388895,17770.324696,10775.501600,8953.849183,9556.147086,18929.870160,17990.138542,18595.803315
MedzilaborceSK,1575.873913,0.000000,687.878762,0.0,0.000000,9757.239935,10040.358348,0.000000,1786.294799,8653.948509,...,1047.005989,0.000000,0.000000,8.000000,10394.870252,13474.171760,0.000000,1380.256828,444.467240,1562.028155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
San Martín de los AndesAR,0.000000,0.000000,0.000000,0.0,0.000000,8168.761492,7965.156469,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,8144.550858,0.000000,0.000000,0.000000,0.000000,0.000000
Phanat NikhomTH,9607.297872,6881.671334,8591.754993,0.0,8107.269985,14836.091950,15009.501352,7930.055793,9415.559394,16747.382327,...,9143.095700,0.000000,0.000000,8235.947917,14740.229715,16961.118781,0.000000,9476.416246,8467.633042,9594.060777
RoanneFR,681.547936,0.000000,0.000000,0.0,0.000000,8885.982100,9155.425883,0.000000,0.000000,7296.913102,...,0.000000,0.000000,0.000000,0.000000,9578.718542,12158.816541,0.000000,0.000000,0.000000,675.084601
KeszthelyHU,1365.602521,0.000000,764.823693,0.0,0.000000,9674.255574,9952.740785,0.000000,1347.597231,8309.499579,...,684.598492,0.000000,0.000000,0.000000,10336.333069,13036.308524,0.000000,1012.817097,0.000000,1352.294888
London_stGB,2.000000,0.000000,0.000000,0.0,0.000000,8341.386815,8617.009881,0.000000,0.000000,7153.913534,...,0.000000,0.000000,0.000000,0.000000,9016.659957,12312.040183,0.000000,0.000000,0.000000,0.000000

In [29]:
#parte messa solo perchè l'utima riga sopra non mi va 
dis = dis.where((dis <= 8), 0) 
dis

ID,LondonGB,QadsayyāSY,SzczecinPL,StratfordNZ,MedzilaborceSK,SabinasMX,Parras de la FuenteMX,DevinBG,AnnabaDZ,CouvaTT,...,SarnenCH,Hà GiangVN,NangandaoCN,HódmezővásárhelyHU,NavolatoMX,San Martín de los AndesAR,Phanat NikhomTH,RoanneFR,KeszthelyHU,London_stGB
ID,,,,,,,,,,,,,,,,,,,,,
LondonGB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
QadsayyāSY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SzczecinPL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
StratfordNZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MedzilaborceSK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
San Martín de los AndesAR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Phanat NikhomTH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RoanneFR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
KeszthelyHU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
London_stGB,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
print(dis)

ID                         LondonGB  QadsayyāSY  SzczecinPL  StratfordNZ  \
ID
LondonGB                        0.0         0.0         0.0          0.0
QadsayyāSY                      0.0         0.0         0.0          0.0
SzczecinPL                      0.0         0.0         0.0          0.0
StratfordNZ                     0.0         0.0         0.0          0.0
MedzilaborceSK                  0.0         0.0         0.0          0.0
...                             ...         ...         ...          ...
San Martín de los AndesAR       0.0         0.0         0.0          0.0
Phanat NikhomTH                 0.0         0.0         0.0          0.0
RoanneFR                        0.0         0.0         0.0          0.0
KeszthelyHU                     0.0         0.0         0.0          0.0
London_stGB                     2.0         0.0         0.0          0.0

ID                         MedzilaborceSK  SabinasMX  Parras de la FuenteMX  \
ID
LondonGB                              0.0        0.0                    0.0
QadsayyāSY                            0.0        0.0                    0.0
SzczecinPL                            0.0        0.0                    0.0
StratfordNZ                           0.0        0.0                    0.0
MedzilaborceSK                        0.0        0.0                    0.0
...                                   ...        ...                    ...
San Martín de los AndesAR             0.0        0.0                    0.0
Phanat NikhomTH                       0.0        0.0                    0.0
RoanneFR                              0.0        0.0                    0.0
KeszthelyHU                           0.0        0.0                    0.0
London_stGB                           0.0        0.0                    0.0

ID                         DevinBG  AnnabaDZ  CouvaTT  ...  SarnenCH  \
ID                                                     ...
LondonGB                       0.0       0.0      0.0  ...       0.0
QadsayyāSY                     0.0       0.0      0.0  ...       0.0
SzczecinPL                     0.0       0.0      0.0  ...       0.0
StratfordNZ                    0.0       0.0      0.0  ...       0.0
MedzilaborceSK                 0.0       0.0      0.0  ...       0.0
...                            ...       ...      ...  ...       ...
San Martín de los AndesAR      0.0       0.0      0.0  ...       0.0
Phanat NikhomTH                0.0       0.0      0.0  ...       0.0
RoanneFR                       0.0       0.0      0.0  ...       0.0
KeszthelyHU                    0.0       0.0      0.0  ...       0.0
London_stGB                    0.0       0.0      0.0  ...       0.0

ID                         Hà GiangVN  NangandaoCN  HódmezővásárhelyHU  \
ID
LondonGB                          0.0          0.0                 0.0
QadsayyāSY                        0.0          0.0                 0.0
SzczecinPL                        0.0          0.0                 0.0
StratfordNZ                       0.0          0.0                 0.0
MedzilaborceSK                    0.0          0.0                 8.0
...                               ...          ...                 ...
San Martín de los AndesAR         0.0          0.0                 0.0
Phanat NikhomTH                   0.0          0.0                 0.0
RoanneFR                          0.0          0.0                 0.0
KeszthelyHU                       0.0          0.0                 0.0
London_stGB                       0.0          0.0                 0.0

ID                         NavolatoMX  San Martín de los AndesAR  \
ID
LondonGB                          0.0                        0.0
QadsayyāSY                        0.0                        0.0
SzczecinPL                        0.0                        0.0
StratfordNZ                       0.0                        0.0
MedzilaborceSK                    0.0                        0.0
...                               ...                        ...
San Martín de los AndesAR         0.0                        0.0
Phanat NikhomTH                   0.0                        0.0
RoanneFR                          0.0                        0.0
KeszthelyHU                       0.0                        0.0
London_stGB                       0.0                        0.0

ID                         Phanat NikhomTH  RoanneFR  KeszthelyHU  London_stGB
ID
LondonGB                               0.0       0.0          0.0          0.0
QadsayyāSY                             0.0       0.0          0.0          0.0
SzczecinPL                             0.0       0.0          0.0          0.0
StratfordNZ                            0.0       0.0          0.0          0.0
MedzilaborceSK                         0.0       0.0          0.0          0.0
...                                    ...       ...          ...          ...
San Martín de los AndesAR              0.0       0.0          0.0          0.0
Phanat NikhomTH                        0.0       0.0          0.0          0.0
RoanneFR                               0.0       0.0          0.0          0.0
KeszthelyHU                            0.0       0.0          0.0          0.0
London_stGB                            0.0       0.0          0.0          0.0

[304 rows x 304 columns]

In [31]:
for i in dis :
    graph[i] = (dis[i] + same_state[i] + pop) * dis[i] / dis[i]
    
graph

ID,LondonGB,QadsayyāSY,SzczecinPL,StratfordNZ,MedzilaborceSK,SabinasMX,Parras de la FuenteMX,DevinBG,AnnabaDZ,CouvaTT,...,SarnenCH,Hà GiangVN,NangandaoCN,HódmezővásárhelyHU,NavolatoMX,San Martín de los AndesAR,Phanat NikhomTH,RoanneFR,KeszthelyHU,London_stGB
ID,,,,,,,,,,,,,,,,,,,,,
LondonGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QadsayyāSY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SzczecinPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StratfordNZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MedzilaborceSK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
San Martín de los AndesAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Phanat NikhomTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RoanneFR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KeszthelyHU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
London_stGB,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
print(graph)

ID                         LondonGB  QadsayyāSY  SzczecinPL  StratfordNZ  \
ID
LondonGB                        NaN         NaN         NaN          NaN
QadsayyāSY                      NaN         NaN         NaN          NaN
SzczecinPL                      NaN         NaN         NaN          NaN
StratfordNZ                     NaN         NaN         NaN          NaN
MedzilaborceSK                  NaN         NaN         NaN          NaN
...                             ...         ...         ...          ...
San Martín de los AndesAR       NaN         NaN         NaN          NaN
Phanat NikhomTH                 NaN         NaN         NaN          NaN
RoanneFR                        NaN         NaN         NaN          NaN
KeszthelyHU                     NaN         NaN         NaN          NaN
London_stGB                     4.0         NaN         NaN          NaN

ID                         MedzilaborceSK  SabinasMX  Parras de la FuenteMX  \
ID
LondonGB                              NaN        NaN                    NaN
QadsayyāSY                            NaN        NaN                    NaN
SzczecinPL                            NaN        NaN                    NaN
StratfordNZ                           NaN        NaN                    NaN
MedzilaborceSK                        NaN        NaN                    NaN
...                                   ...        ...                    ...
San Martín de los AndesAR             NaN        NaN                    NaN
Phanat NikhomTH                       NaN        NaN                    NaN
RoanneFR                              NaN        NaN                    NaN
KeszthelyHU                           NaN        NaN                    NaN
London_stGB                           NaN        NaN                    NaN

ID                         DevinBG  AnnabaDZ  CouvaTT  ...  SarnenCH  \
ID                                                     ...
LondonGB                       NaN       NaN      NaN  ...       NaN
QadsayyāSY                     NaN       NaN      NaN  ...       NaN
SzczecinPL                     NaN       NaN      NaN  ...       NaN
StratfordNZ                    NaN       NaN      NaN  ...       NaN
MedzilaborceSK                 NaN       NaN      NaN  ...       NaN
...                            ...       ...      ...  ...       ...
San Martín de los AndesAR      NaN       NaN      NaN  ...       NaN
Phanat NikhomTH                NaN       NaN      NaN  ...       NaN
RoanneFR                       NaN       NaN      NaN  ...       NaN
KeszthelyHU                    NaN       NaN      NaN  ...       NaN
London_stGB                    NaN       NaN      NaN  ...       NaN

ID                         Hà GiangVN  NangandaoCN  HódmezővásárhelyHU  \
ID
LondonGB                          NaN          NaN                 NaN
QadsayyāSY                        NaN          NaN                 NaN
SzczecinPL                        NaN          NaN                 NaN
StratfordNZ                       NaN          NaN                 NaN
MedzilaborceSK                    NaN          NaN                10.0
...                               ...          ...                 ...
San Martín de los AndesAR         NaN          NaN                 NaN
Phanat NikhomTH                   NaN          NaN                 NaN
RoanneFR                          NaN          NaN                 NaN
KeszthelyHU                       NaN          NaN                 NaN
London_stGB                       NaN          NaN                 NaN

ID                         NavolatoMX  San Martín de los AndesAR  \
ID
LondonGB                          NaN                        NaN
QadsayyāSY                        NaN                        NaN
SzczecinPL                        NaN                        NaN
StratfordNZ                       NaN                        NaN
MedzilaborceSK                    NaN                        NaN
...                               ...                        ...
San Martín de los AndesAR         NaN                        NaN
Phanat NikhomTH                   NaN                        NaN
RoanneFR                          NaN                        NaN
KeszthelyHU                       NaN                        NaN
London_stGB                       NaN                        NaN

ID                         Phanat NikhomTH  RoanneFR  KeszthelyHU  London_stGB
ID
LondonGB                               NaN       NaN          NaN          NaN
QadsayyāSY                             NaN       NaN          NaN          NaN
SzczecinPL                             NaN       NaN          NaN          NaN
StratfordNZ                            NaN       NaN          NaN          NaN
MedzilaborceSK                         NaN       NaN          NaN          NaN
...                                    ...       ...          ...          ...
San Martín de los AndesAR              NaN       NaN          NaN          NaN
Phanat NikhomTH                        NaN       NaN          NaN          NaN
RoanneFR                               NaN       NaN          NaN          NaN
KeszthelyHU                            NaN       NaN          NaN          NaN
London_stGB                            NaN       NaN          NaN          NaN

[304 rows x 304 columns]

In [33]:
# parte messa solo perchè l'utima riga sopra non mi va 
graph = graph.where((graph > 1), 0) 
graph = graph.T # dataframe (la trasposta è per mettere i pesi sulle righe o sulle colonne)

In [34]:
## un tentativo con networkX (mi prende il peso minore però----)

import networkx as nx

In [38]:
## creo grafo con networkX direzionato da graph cheè matrice di adiacenza non simmetrica
D = nx.from_pandas_adjacency(graph, create_using = nx.DiGraph)

In [39]:
## visualizzo i nodi
D.nodes()

NodeView(('LondonGB', 'QadsayyāSY', 'SzczecinPL', 'StratfordNZ', 'MedzilaborceSK', 'SabinasMX', 'Parras de la FuenteMX', 'DevinBG', 'AnnabaDZ', 'CouvaTT', 'MoussoroTD', 'ChaumontFR', 'ProvidenceUS', 'BenderMD', 'KampotKH', 'AbéchéTD', 'JijigaET', 'GibaraCU', 'ChiquimulaGT', 'TartagalAR', 'KauhavaFI', 'NašiceHR', 'PraiaCV', 'KhŭjandTJ', 'KurikkaFI', 'CunduacánMX', 'KłodzkoPL', 'ZariaNG', 'KriževciHR', 'CanberraAU', 'TakābIR', 'HanauDE', 'IndianapolisUS', 'PortimãoPT', 'NawáSY', 'Biên HòaVN', 'SopronHU', 'BalkhAF', 'DongningCN', 'CarlowIE', 'TindoufDZ', 'LeerDE', 'TrogirHR', 'OberhausenDE', 'AbasoloMX', 'SalskRU', 'LeobenAT', 'OstravaCZ', 'AbakanRU', 'CoutancesFR', 'PaideEE', 'BijeljinaBA', 'PeshteraBG', 'ŌtsuJP', 'SanmingCN', 'WuhaiCN', 'PolokwaneZA', 'AmbatondrazakaMG', 'Urgut ShahriUZ', 'CloppenburgDE', '‘IbrīOM', 'DarmstadtDE', 'KoutialaML', 'OdemiraPT', 'MusomaTZ', 'ZapopanMX', 'KissidougouGN', 'Ciudad Guadalupe VictoriaMX', 'AstravyetsBY', 'JilotepecMX', 'Santa AnaMX', 'Mo i RanaNO', 'BordeauxFR', 'EbebiyínGQ', 'AtlatlahucanMX', 'TangdukouCN', 'Port-au-PrinceHT', 'GiurgiuRO', 'HyesanKP', 'BenghaziLY', 'KathuTH', 'Bayt al FaqīhYE', 'KismaayoSO', 'OsogboNG', 'WolfenbüttelDE', 'YayladağıTR', 'Los ÁngelesCL', 'SlatinaRO', 'PlevenBG', 'MoscowRU', 'JinchengCN', 'YakacıkTR', 'OrëlRU', 'Tlahualilo de ZaragozaMX', 'Birnin KonniNE', 'YichengCN', 'General ConesaAR', 'Santiago PapasquiaroMX', 'Pak ChongTH', 'Novo MestoSI', 'AvellanedaAR', 'Las HerasAR', 'KermānIR', 'LitynUA', 'Baden-BadenDE', 'Kampong SpeuKH', 'KostromaRU', 'OyoNG', 'BrzozówPL', 'TüriEE', 'MuşTR', 'LabinHR', 'KemptenDE', 'NguigmiNE', 'IeperBE', 'Santo Domingo de los ColoradosEC', 'LorientFR', 'Al QunayţirahSY', 'ZmiivUA', 'SonnebergDE', 'Amatlán de los ReyesMX', 'AlavusFI', 'CadereytaMX', 'PrévezaGR', 'XigazêCN', 'JawharSO', 'LokhvytsyaUA', 'TunapunaTT', 'Butha-ButheLS', 'RathenowDE', 'ZwolleNL', 'Ciudad VallesMX', 'KarlstadSE', 'MakurdiNG', 'Ciro RedondoCU', 'RaleighUS', 'KorenovskRU', 'AltöttingDE', 'BarranquillaCO', 'PakwachUG', 'Hanga RoaCL', 'Aţ ŢafīlahJO', 'AllendeMX', 'San IgnacioBZ', 'Montego BayJM', 'GaopingCN', 'ZempoalaMX', 'SloboziaRO', 'BarrancabermejaCO', 'SarkadHU', 'NicosiaCY', 'LinaresCL', 'QuelimaneMZ', 'YozgatTR', 'PamplonaES', 'TandilAR', 'ToijalaFI', 'SvendborgDK', 'KumiUG', 'VarshetsBG', 'NeibaDO', 'KengeCD', 'YaoundéCM', 'Yoshkar-OlaRU', 'ZhongshanCN', 'TaitungTW', 'ZuwārahLY', 'KaiserslauternDE', 'SmolenskRU', 'KumulCN', 'MaşyāfSY', 'Târgu JiuRO', 'HuangshiCN', 'MinskBY', 'São LuísBR', 'RomeIT', 'BrestFR', 'WeimarDE', 'RosarioAR', 'Kaga BandoroCF', 'ColumbusUS', 'Bandar ‘AbbāsIR', 'SkrundaLV', 'HararET', 'Ştefan VodăMD', 'MchinjiMW', 'StryyUA', 'ArnhemNL', 'HailinCN', 'Amecameca de JuárezMX', 'ArushaTZ', 'Maha SarakhamTH', 'KrotoszynPL', 'SlutskBY', 'HohhotCN', 'HonoluluUS', 'Dayr ḨāfirSY', 'AmstettenAT', 'KasserineTN', 'OkaraPK', 'TalsiLV', 'Santa ClaraCU', 'La CeibaHN', 'Umm al QaywaynAE', 'UlaangomMN', 'Tixtla de GuerreroMX', 'YasynuvataUA', 'HalmstadSE', 'NaumburgDE', 'ZürichCH', 'Villefranche-sur-SaôneFR', 'RēzekneLV', 'České BudějoviceCZ', 'HrastnikSI', 'EsperanzaAR', 'KérkyraGR', 'SousseTN', 'BanyuwangiID', 'TokatTR', 'WarendorfDE', 'CampanaAR', 'ShuanghejiedaoCN', 'HezeCN', 'KrupinaSK', 'San BuenaventuraMX', 'BraunschweigDE', 'SkenderajXK', 'ZadarHR', 'HisorTJ', 'Autlán de NavarroMX', 'GenheCN', 'MikkeliFI', 'Castro MarimPT', 'TacnaPE', 'SoissonsFR', 'San Antonio del TáchiraVE', 'KutnoPL', 'AharIR', 'YaypanUZ', 'TallkalakhSY', 'DzuunmodMN', 'PanevėžysLT', 'Kattaqo’rg’on ShahriUZ', 'LaghouatDZ', 'BiałystokPL', 'As SamāwahIQ', 'Pak KretTH', 'KreuzlingenCH', 'Gorzów WielkopolskiPL', 'Homyel’BY', 'FlorenceIT', 'ValdiviaCL', 'AnuradhapuraLK', 'DebarMK', 'TataouineTN', 'NacajucaMX', 'SárvárHU', 'GbadoliteCD', 'AtarMR', 'YāsūjIR', 'IquitosPE', 'MontaubanFR', 'Chos MalalAR', 'GuatireVE', 'Aţ ŢūrEG', 'SinguilucanMX', 'RotterdamNL', 'GouréNE', 'Wiener NeustadtAT', 'IxtencoMX', 'TayoltitaMX', 'Oroqen ZizhiqiCN', 'NarvaEE', 'Ixtapan del OroMX', 'RadovišMK', 'LuandaAO', 'FočaBA', 'GoraždeBA', 'ZhashkivUA', 'NorakTJ', 'MaaseikBE', 'Annaberg-BuchholzDE', 'AlajuelaCR', 'NurmesFI', 'Puerto CabelloVE', 'GizaEG', 'LeónES', 'FuntuaNG', 'KasurPK', 'DoloresAR', 'JanjanburehGM', 'Buôn Ma ThuộtVN', 'Krems an der DonauAT', 'LucenaPH', 'SarnenCH', 'Hà GiangVN', 'NangandaoCN', 'HódmezővásárhelyHU', 'NavolatoMX', 'San Martín de los AndesAR', 'Phanat NikhomTH', 'RoanneFR', 'KeszthelyHU', 'London_stGB'))

In [40]:
## link all'algoritmo usato
## https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.single_source_dijkstra.html#networkx.algorithms.shortest_paths.weighted.single_source_dijkstra
length, path = nx.single_source_dijkstra(D, source = 'London_stGB', target = 'LondonGB')
print(length)
print(path)

NetworkXNoPath: No path to LondonGB.

In [ ]:
## visualizzo D grafo direzionato
nx.draw(D)

In [ ]:
## se vogliamo altri formati
## gr_array = np.array(graph) ## array

In [ ]:
## list
## gr_ls = gr_array.tolist()
## print(gr_ls)

In [ ]:
## type(gr_ls)

In [ ]:
# GR = nx.from_numpy_array(gr_array)
# GR.edges(data=True)

In [ ]:
## GR.nodes()

In [ ]:
## nx.shortest_path(GR, source = 0, target = 271)