In [1]:
## import data manipulation packages
import pandas as pd
import numpy as np
from sklearn.neighbors import DistanceMetric
from math import radians

## import dataset as variable 'city' and drop NaN
cities = pd.read_excel('data/small_cities.xlsx')
ct = cities.dropna(axis = 'rows', how = 'any')

## concatenate iso2 and city to get unique id
## ct['ID'] = ct['city'].map(str) + ct['iso2'].map(str)

In [2]:
#add london Start
London_st = ct.loc[(ct['city'] == 'London') & (ct['iso3'] == 'GBR')]
London_st['city']='London_st' 
London_st['lng'] = London_st['lng'] + 0.2

<ipython-input-2-f4fa982cdf22>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  London_st['city']='London_st'
<ipython-input-2-f4fa982cdf22>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  London_st['lng'] = London_st['lng'] + 0.2

In [3]:
ct = ct.append(London_st)

In [4]:
ct = ct.reset_index()
print(ct)

    index          city    city_ascii      lat       lng         country iso2  \
0       0         Tokyo         Tokyo  35.6897  139.6922           Japan   JP
1       1       Jakarta       Jakarta  -6.2146  106.8451       Indonesia   ID
2       2         Delhi         Delhi  28.6600   77.2300           India   IN
3       3        Mumbai        Mumbai  18.9667   72.8333           India   IN
4       4        Manila        Manila  14.5958  120.9772     Philippines   PH
5       5      Shanghai      Shanghai  31.1667  121.4667           China   CN
6       6     São Paulo     Sao Paulo -23.5504  -46.6339          Brazil   BR
7       7         Seoul         Seoul  37.5833  127.0000    Korea, South   KR
8       8   Mexico City   Mexico City  19.4333  -99.1333          Mexico   MX
9       9     Guangzhou     Guangzhou  23.1288  113.2590           China   CN
10     10       Beijing       Beijing  39.9050  116.3914           China   CN
11     11         Cairo         Cairo  30.0561   31.2394           Egypt   EG
12     13       Kolkāta       Kolkata  22.5411   88.3378           India   IN
13     14        Moscow        Moscow  55.7558   37.6178          Russia   RU
14     15       Bangkok       Bangkok  13.7500  100.5167        Thailand   TH
15     16  Buenos Aires  Buenos Aires -34.5997  -58.3819       Argentina   AR
16     17      Shenzhen      Shenzhen  22.5350  114.0540           China   CN
17     18         Dhaka         Dhaka  23.7161   90.3961      Bangladesh   BD
18     19        London        London  51.5072   -0.1275  United Kingdom   GB
19     19     London_st        London  51.5072    0.0725  United Kingdom   GB

   iso3                        admin_name  capital  population          id
0   JPN                             Tōkyō  primary    37977000  1392685764
1   IDN                           Jakarta  primary    34540000  1360771077
2   IND                             Delhi    admin    29617000  1356872604
3   IND                       Mahārāshtra    admin    23355000  1356226629
4   PHL                            Manila  primary    23088000  1608618140
5   CHN                          Shanghai    admin    22120000  1156073548
6   BRA                         São Paulo    admin    22046000  1076532519
7   KOR                             Seoul  primary    21794000  1410836482
8   MEX                  Ciudad de México  primary    20996000  1484247881
9   CHN                         Guangdong    admin    20902000  1156237133
10  CHN                           Beijing  primary    19433000  1156228865
11  EGY                        Al Qāhirah  primary    19372000  1818253931
12  IND                       West Bengal    admin    17560000  1356060520
13  RUS                            Moskva  primary    17125000  1643318494
14  THA            Krung Thep Maha Nakhon  primary    17066000  1764068610
15  ARG  Buenos Aires, Ciudad Autónoma de  primary    16157000  1032717330
16  CHN                         Guangdong    minor    15929000  1156158707
17  BGD                             Dhaka  primary    15443000  1050529279
18  GBR                   London, City of  primary    10979000  1826645935
19  GBR                   London, City of  primary    10979000  1826645935

In [5]:
## concatenate iso2 and city to get unique id
ct['ID'] = ct['city'].map(str) + ct['iso2'].map(str)

In [6]:
## drop not usable columns
ct = ct.drop(['city_ascii', 'country', 'iso2', 'admin_name', 'capital', 'id'], axis = 1)

In [7]:
 ct = ct.drop('index', axis = 1)

In [8]:
#population
pop = np.where(ct['population']< 200000 , 0 , 2 )
#same state 
zero_data = np.ones(shape=(len(ct),len(ct)))
st = pd.DataFrame(zero_data , columns = ct['iso3'], index = ct['iso3'])
for i in ct['iso3']:
    st.loc[ i , i ] = 0   
st = st * 2

In [9]:
print(st)

iso3  JPN  IDN  IND  IND  PHL  CHN  BRA  KOR  MEX  CHN  CHN  EGY  IND  RUS  \
iso3
JPN   0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
IDN   2.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
IND   2.0  2.0  0.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0
IND   2.0  2.0  0.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0
PHL   2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  0.0  0.0  2.0  2.0  2.0
BRA   2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
KOR   2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0
MEX   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  0.0  0.0  2.0  2.0  2.0
CHN   2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  0.0  0.0  2.0  2.0  2.0
EGY   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0
IND   2.0  2.0  0.0  0.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0  2.0
RUS   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  0.0
THA   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
ARG   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  2.0  0.0  0.0  2.0  2.0  2.0
BGD   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
GBR   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0
GBR   2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0

iso3  THA  ARG  CHN  BGD  GBR  GBR
iso3
JPN   2.0  2.0  2.0  2.0  2.0  2.0
IDN   2.0  2.0  2.0  2.0  2.0  2.0
IND   2.0  2.0  2.0  2.0  2.0  2.0
IND   2.0  2.0  2.0  2.0  2.0  2.0
PHL   2.0  2.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  0.0  2.0  2.0  2.0
BRA   2.0  2.0  2.0  2.0  2.0  2.0
KOR   2.0  2.0  2.0  2.0  2.0  2.0
MEX   2.0  2.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  0.0  2.0  2.0  2.0
CHN   2.0  2.0  0.0  2.0  2.0  2.0
EGY   2.0  2.0  2.0  2.0  2.0  2.0
IND   2.0  2.0  2.0  2.0  2.0  2.0
RUS   2.0  2.0  2.0  2.0  2.0  2.0
THA   0.0  2.0  2.0  2.0  2.0  2.0
ARG   2.0  0.0  2.0  2.0  2.0  2.0
CHN   2.0  2.0  0.0  2.0  2.0  2.0
BGD   2.0  2.0  2.0  0.0  2.0  2.0
GBR   2.0  2.0  2.0  2.0  0.0  0.0
GBR   2.0  2.0  2.0  2.0  0.0  0.0

In [10]:
#direction (changed to longitude)
dr_x = np.where(ct['lng']>= 0 , ct['lng'] , (ct['lng'] + 150) + 150 )
dr_y = np.where(ct['lng']>= 0 , ct['lng'] , (ct['lng'] + 150) + 150 )

# dr_x = ct['lng'] + 180
# dr_y = ct['lng'] + 180

drdf = pd.DataFrame(zero_data , columns = dr_x, index = dr_y)
for i in dr_x:
    for e in dr_y: 
        drdf.loc[i , e] = np.where( i >= e , 0 , 1 )

In [11]:
print(drdf)

          139.6922  106.8451  77.2300   72.8333   120.9772  121.4667  \
139.6922       0.0       0.0       0.0       0.0       0.0       0.0
106.8451       1.0       0.0       0.0       0.0       1.0       1.0
77.2300        1.0       1.0       0.0       0.0       1.0       1.0
72.8333        1.0       1.0       1.0       0.0       1.0       1.0
120.9772       1.0       0.0       0.0       0.0       0.0       1.0
121.4667       1.0       0.0       0.0       0.0       0.0       0.0
253.3661       0.0       0.0       0.0       0.0       0.0       0.0
127.0000       1.0       0.0       0.0       0.0       0.0       0.0
200.8667       0.0       0.0       0.0       0.0       0.0       0.0
113.2590       1.0       0.0       0.0       0.0       1.0       1.0
116.3914       1.0       0.0       0.0       0.0       1.0       1.0
31.2394        1.0       1.0       1.0       1.0       1.0       1.0
88.3378        1.0       1.0       0.0       0.0       1.0       1.0
37.6178        1.0       1.0       1.0       1.0       1.0       1.0
100.5167       1.0       1.0       0.0       0.0       1.0       1.0
241.6181       0.0       0.0       0.0       0.0       0.0       0.0
114.0540       1.0       0.0       0.0       0.0       1.0       1.0
90.3961        1.0       1.0       0.0       0.0       1.0       1.0
299.8725       0.0       0.0       0.0       0.0       0.0       0.0
0.0725         1.0       1.0       1.0       1.0       1.0       1.0

          253.3661  127.0000  200.8667  113.2590  116.3914  31.2394   \
139.6922       1.0       0.0       1.0       0.0       0.0       0.0
106.8451       1.0       1.0       1.0       1.0       1.0       0.0
77.2300        1.0       1.0       1.0       1.0       1.0       0.0
72.8333        1.0       1.0       1.0       1.0       1.0       0.0
120.9772       1.0       1.0       1.0       0.0       0.0       0.0
121.4667       1.0       1.0       1.0       0.0       0.0       0.0
253.3661       0.0       0.0       0.0       0.0       0.0       0.0
127.0000       1.0       0.0       1.0       0.0       0.0       0.0
200.8667       1.0       0.0       0.0       0.0       0.0       0.0
113.2590       1.0       1.0       1.0       0.0       1.0       0.0
116.3914       1.0       1.0       1.0       0.0       0.0       0.0
31.2394        1.0       1.0       1.0       1.0       1.0       0.0
88.3378        1.0       1.0       1.0       1.0       1.0       0.0
37.6178        1.0       1.0       1.0       1.0       1.0       0.0
100.5167       1.0       1.0       1.0       1.0       1.0       0.0
241.6181       1.0       0.0       0.0       0.0       0.0       0.0
114.0540       1.0       1.0       1.0       0.0       1.0       0.0
90.3961        1.0       1.0       1.0       1.0       1.0       0.0
299.8725       0.0       0.0       0.0       0.0       0.0       0.0
0.0725         1.0       1.0       1.0       1.0       1.0       1.0

          88.3378   37.6178   100.5167  241.6181  114.0540  90.3961   \
139.6922       0.0       0.0       0.0       1.0       0.0       0.0
106.8451       0.0       0.0       0.0       1.0       1.0       0.0
77.2300        1.0       0.0       1.0       1.0       1.0       1.0
72.8333        1.0       0.0       1.0       1.0       1.0       1.0
120.9772       0.0       0.0       0.0       1.0       0.0       0.0
121.4667       0.0       0.0       0.0       1.0       0.0       0.0
253.3661       0.0       0.0       0.0       0.0       0.0       0.0
127.0000       0.0       0.0       0.0       1.0       0.0       0.0
200.8667       0.0       0.0       0.0       1.0       0.0       0.0
113.2590       0.0       0.0       0.0       1.0       1.0       0.0
116.3914       0.0       0.0       0.0       1.0       0.0       0.0
31.2394        1.0       1.0       1.0       1.0       1.0       1.0
88.3378        0.0       0.0       1.0       1.0       1.0       1.0
37.6178        1.0       0.0       1.0       1.0       1.0       1.0
100.5167       0.0       0.0       0.0       1.0       1.0       0.0
241.6181       0.0       0.0       0.0       0.0       0.0       0.0
114.0540       0.0       0.0       0.0       1.0       0.0       0.0
90.3961        0.0       0.0       1.0       1.0       1.0       0.0
299.8725       0.0       0.0       0.0       0.0       0.0       0.0
0.0725         1.0       1.0       1.0       1.0       1.0       1.0

          299.8725  0.0725
139.6922       1.0       0.0
106.8451       1.0       0.0
77.2300        1.0       0.0
72.8333        1.0       0.0
120.9772       1.0       0.0
121.4667       1.0       0.0
253.3661       1.0       0.0
127.0000       1.0       0.0
200.8667       1.0       0.0
113.2590       1.0       0.0
116.3914       1.0       0.0
31.2394        1.0       0.0
88.3378        1.0       0.0
37.6178        1.0       0.0
100.5167       1.0       0.0
241.6181       1.0       0.0
114.0540       1.0       0.0
90.3961        1.0       0.0
299.8725       0.0       0.0
0.0725         1.0       0.0

In [12]:
#metto i giusti indici alle matrici 
direction = pd.DataFrame(drdf.to_numpy() , columns = ct['ID'], index = ct['ID'])
same_state = pd.DataFrame(st.to_numpy() , columns = ct['ID'], index = ct['ID'])
population = pd.DataFrame(pop , index = ct['ID'])

In [13]:
print(direction)

ID              TokyoJP  JakartaID  DelhiIN  MumbaiIN  ManilaPH  ShanghaiCN  \
ID
TokyoJP             0.0        0.0      0.0       0.0       0.0         0.0
JakartaID           1.0        0.0      0.0       0.0       1.0         1.0
DelhiIN             1.0        1.0      0.0       0.0       1.0         1.0
MumbaiIN            1.0        1.0      1.0       0.0       1.0         1.0
ManilaPH            1.0        0.0      0.0       0.0       0.0         1.0
ShanghaiCN          1.0        0.0      0.0       0.0       0.0         0.0
São PauloBR         0.0        0.0      0.0       0.0       0.0         0.0
SeoulKR             1.0        0.0      0.0       0.0       0.0         0.0
Mexico CityMX       0.0        0.0      0.0       0.0       0.0         0.0
GuangzhouCN         1.0        0.0      0.0       0.0       1.0         1.0
BeijingCN           1.0        0.0      0.0       0.0       1.0         1.0
CairoEG             1.0        1.0      1.0       1.0       1.0         1.0
KolkātaIN           1.0        1.0      0.0       0.0       1.0         1.0
MoscowRU            1.0        1.0      1.0       1.0       1.0         1.0
BangkokTH           1.0        1.0      0.0       0.0       1.0         1.0
Buenos AiresAR      0.0        0.0      0.0       0.0       0.0         0.0
ShenzhenCN          1.0        0.0      0.0       0.0       1.0         1.0
DhakaBD             1.0        1.0      0.0       0.0       1.0         1.0
LondonGB            0.0        0.0      0.0       0.0       0.0         0.0
London_stGB         1.0        1.0      1.0       1.0       1.0         1.0

ID              São PauloBR  SeoulKR  Mexico CityMX  GuangzhouCN  BeijingCN  \
ID
TokyoJP                 1.0      0.0            1.0          0.0        0.0
JakartaID               1.0      1.0            1.0          1.0        1.0
DelhiIN                 1.0      1.0            1.0          1.0        1.0
MumbaiIN                1.0      1.0            1.0          1.0        1.0
ManilaPH                1.0      1.0            1.0          0.0        0.0
ShanghaiCN              1.0      1.0            1.0          0.0        0.0
São PauloBR             0.0      0.0            0.0          0.0        0.0
SeoulKR                 1.0      0.0            1.0          0.0        0.0
Mexico CityMX           1.0      0.0            0.0          0.0        0.0
GuangzhouCN             1.0      1.0            1.0          0.0        1.0
BeijingCN               1.0      1.0            1.0          0.0        0.0
CairoEG                 1.0      1.0            1.0          1.0        1.0
KolkātaIN               1.0      1.0            1.0          1.0        1.0
MoscowRU                1.0      1.0            1.0          1.0        1.0
BangkokTH               1.0      1.0            1.0          1.0        1.0
Buenos AiresAR          1.0      0.0            0.0          0.0        0.0
ShenzhenCN              1.0      1.0            1.0          0.0        1.0
DhakaBD                 1.0      1.0            1.0          1.0        1.0
LondonGB                0.0      0.0            0.0          0.0        0.0
London_stGB             1.0      1.0            1.0          1.0        1.0

ID              CairoEG  KolkātaIN  MoscowRU  BangkokTH  Buenos AiresAR  \
ID
TokyoJP             0.0        0.0       0.0        0.0             1.0
JakartaID           0.0        0.0       0.0        0.0             1.0
DelhiIN             0.0        1.0       0.0        1.0             1.0
MumbaiIN            0.0        1.0       0.0        1.0             1.0
ManilaPH            0.0        0.0       0.0        0.0             1.0
ShanghaiCN          0.0        0.0       0.0        0.0             1.0
São PauloBR         0.0        0.0       0.0        0.0             0.0
SeoulKR             0.0        0.0       0.0        0.0             1.0
Mexico CityMX       0.0        0.0       0.0        0.0             1.0
GuangzhouCN         0.0        0.0       0.0        0.0             1.0
BeijingCN           0.0        0.0       0.0        0.0             1.0
CairoEG             0.0        1.0       1.0        1.0             1.0
KolkātaIN           0.0        0.0       0.0        1.0             1.0
MoscowRU            0.0        1.0       0.0        1.0             1.0
BangkokTH           0.0        0.0       0.0        0.0             1.0
Buenos AiresAR      0.0        0.0       0.0        0.0             0.0
ShenzhenCN          0.0        0.0       0.0        0.0             1.0
DhakaBD             0.0        0.0       0.0        1.0             1.0
LondonGB            0.0        0.0       0.0        0.0             0.0
London_stGB         1.0        1.0       1.0        1.0             1.0

ID              ShenzhenCN  DhakaBD  LondonGB  London_stGB
ID
TokyoJP                0.0      0.0       1.0          0.0
JakartaID              1.0      0.0       1.0          0.0
DelhiIN                1.0      1.0       1.0          0.0
MumbaiIN               1.0      1.0       1.0          0.0
ManilaPH               0.0      0.0       1.0          0.0
ShanghaiCN             0.0      0.0       1.0          0.0
São PauloBR            0.0      0.0       1.0          0.0
SeoulKR                0.0      0.0       1.0          0.0
Mexico CityMX          0.0      0.0       1.0          0.0
GuangzhouCN            1.0      0.0       1.0          0.0
BeijingCN              0.0      0.0       1.0          0.0
CairoEG                1.0      1.0       1.0          0.0
KolkātaIN              1.0      1.0       1.0          0.0
MoscowRU               1.0      1.0       1.0          0.0
BangkokTH              1.0      0.0       1.0          0.0
Buenos AiresAR         0.0      0.0       1.0          0.0
ShenzhenCN             0.0      0.0       1.0          0.0
DhakaBD                1.0      0.0       1.0          0.0
LondonGB               0.0      0.0       0.0          0.0
London_stGB            1.0      1.0       1.0          0.0

In [14]:
## coversion of coordinated in degrees to radians
ct['lat'] = np.radians(ct['lat'])
ct['lng'] = np.radians(ct['lng'])

In [15]:
## get the scipy metrics
dist = DistanceMetric.get_metric('haversine')

In [16]:
## prepare the array to get in input for the distance calculation
ct[['lat','lng']].to_numpy()

array([[ 6.22902774e-01,  2.43808883e+00],
       [-1.08465232e-01,  1.86479878e+00],
       [ 5.00211364e-01,  1.34791778e+00],
       [ 3.31031363e-01,  1.27118089e+00],
       [ 2.54744767e-01,  2.11145046e+00],
       [ 5.43961532e-01,  2.11999385e+00],
       [-4.11032020e-01, -8.13915098e-01],
       [ 6.55952329e-01,  2.21656815e+00],
       [ 3.39175070e-01, -1.73020248e+00],
       [ 4.03673712e-01,  1.97674246e+00],
       [ 6.96473638e-01,  2.03141315e+00],
       [ 5.24577905e-01,  5.45230386e-01],
       [ 3.93416412e-01,  1.54178546e+00],
       [ 9.73122287e-01,  6.56554467e-01],
       [ 2.39982772e-01,  1.75434737e+00],
       [-6.03878685e-01, -1.01895638e+00],
       [ 3.93309947e-01,  1.99061783e+00],
       [ 4.13924031e-01,  1.57770958e+00],
       [ 8.98970228e-01, -2.22529480e-03],
       [ 8.98970228e-01,  1.26536371e-03]])

In [17]:
## pass pairwise function to get the distance / multiply for 6373 as earth sperical radius is 6373kms
dist.pairwise(ct [['lat','lng']].to_numpy())*6373

array([[0.00000000e+00, 5.78790377e+03, 5.83524850e+03, 6.73636810e+03,
        2.99719434e+03, 1.76202239e+03, 1.85399852e+04, 1.15130789e+03,
        1.13093804e+04, 2.90380048e+03, 2.09445551e+03, 9.56623330e+03,
        5.13914282e+03, 7.48057052e+03, 4.60365728e+03, 1.83753446e+04,
        2.87585310e+03, 4.89188601e+03, 9.56172023e+03, 9.55443116e+03],
       [5.78790377e+03, 0.00000000e+00, 5.01126757e+03, 4.66228762e+03,
        2.79071769e+03, 4.43907373e+03, 1.56332708e+04, 5.30108500e+03,
        1.68508222e+04, 3.33752354e+03, 5.22260347e+03, 8.98864387e+03,
        3.78003420e+03, 9.31518347e+03, 2.32800381e+03, 1.52238172e+04,
        3.29270141e+03, 3.77792978e+03, 1.17222779e+04, 1.17086198e+04],
       [5.83524850e+03, 5.01126757e+03, 0.00000000e+00, 1.16699746e+03,
        4.75533799e+03, 4.24589965e+03, 1.44355433e+04, 4.68601564e+03,
        1.46577056e+04, 3.64336139e+03, 3.77541615e+03, 4.43087846e+03,
        1.30460655e+03, 4.34081998e+03, 2.91941239e+03, 1.57997341e+04,
        3.74119869e+03, 1.42338249e+03, 6.71110194e+03, 6.69745560e+03],
       [6.73636810e+03, 4.66228762e+03, 1.16699746e+03, 0.00000000e+00,
        5.13501293e+03, 5.04231712e+03, 1.37705323e+04, 5.60966494e+03,
        1.56611326e+04, 4.20900139e+03, 4.75595358e+03, 4.36017510e+03,
        1.65997637e+03, 5.03819453e+03, 3.00745563e+03, 1.49297544e+04,
        4.29278017e+03, 1.89304386e+03, 7.20001131e+03, 7.18616719e+03],
       [2.99719434e+03, 2.79071769e+03, 4.75533799e+03, 5.13501293e+03,
        0.00000000e+00, 1.84385359e+03, 1.83834440e+04, 2.62511530e+03,
        1.42249132e+04, 1.24862455e+03, 2.85035977e+03, 9.17954846e+03,
        3.54483216e+03, 8.25982951e+03, 2.20781502e+03, 1.77954113e+04,
        1.14520933e+03, 3.36105731e+03, 1.07383397e+04, 1.07267806e+04],
       [1.76202239e+03, 4.43907373e+03, 4.24589965e+03, 5.04231712e+03,
        1.84385359e+03, 0.00000000e+00, 1.85740240e+04, 8.75628928e+02,
        1.29176388e+04, 1.20710231e+03, 1.07454889e+03, 8.35907920e+03,
        3.41014569e+03, 6.82431572e+03, 2.88594371e+03, 1.96392564e+04,
        1.20870378e+03, 3.16541873e+03, 9.20525753e+03, 9.19507278e+03],
       [1.85399852e+04, 1.56332708e+04, 1.44355433e+04, 1.37705323e+04,
        1.83834440e+04, 1.85740240e+04, 0.00000000e+00, 1.83468081e+04,
        7.43435645e+03, 1.79690103e+04, 1.76036931e+04, 1.02238021e+04,
        1.54304662e+04, 1.18101747e+04, 1.64020562e+04, 1.67507494e+03,
        1.80429372e+04, 1.56599317e+04, 9.50039762e+03, 9.50965010e+03],
       [1.15130789e+03, 5.30108500e+03, 4.68601564e+03, 5.60966494e+03,
        2.62511530e+03, 8.75628928e+02, 1.83468081e+04, 0.00000000e+00,
        1.20526597e+04, 2.07446508e+03, 9.55203445e+02, 8.48821458e+03,
        4.04410186e+03, 6.60741886e+03, 3.72545776e+03, 1.94349063e+04,
        2.08214705e+03, 3.79635060e+03, 8.85950223e+03, 8.85059619e+03],
       [1.13093804e+04, 1.68508222e+04, 1.46577056e+04, 1.56611326e+04,
        1.42249132e+04, 1.29176388e+04, 7.43435645e+03, 1.20526597e+04,
        0.00000000e+00, 1.41244987e+04, 1.24626239e+04, 1.23718641e+04,
        1.52825315e+04, 1.07227120e+04, 1.57489782e+04, 7.39422032e+03,
        1.41231828e+04, 1.51118544e+04, 8.93150563e+03, 8.94458329e+03],
       [2.90380048e+03, 3.33752354e+03, 3.64336139e+03, 4.20900139e+03,
        1.24862455e+03, 1.20710231e+03, 1.79690103e+04, 2.07446508e+03,
        1.41244987e+04, 0.00000000e+00, 1.88914677e+03, 8.02045008e+03,
        2.55247000e+03, 7.01426949e+03, 1.69998871e+03, 1.85092668e+04,
        1.04901769e+02, 2.33190811e+03, 9.49876880e+03, 9.48703401e+03],
       [2.09445551e+03, 5.22260347e+03, 3.77541615e+03, 4.75595358e+03,
        2.85035977e+03, 1.07454889e+03, 1.76036931e+04, 9.55203445e+02,
        1.24626239e+04, 1.88914677e+03, 0.00000000e+00, 7.54431231e+03,
        3.27053352e+03, 5.79457072e+03, 3.29636877e+03, 1.92717738e+04,
        1.94460715e+03, 3.02716629e+03, 8.14274683e+03, 8.13280842e+03],
       [9.56623330e+03, 8.98864387e+03, 4.43087846e+03, 4.36017510e+03,
        9.17954846e+03, 8.35907920e+03, 1.02238021e+04, 8.48821458e+03,
        1.23718641e+04, 8.02045008e+03, 7.54431231e+03, 0.00000000e+00,
        5.69796426e+03, 2.90256577e+03, 7.27266148e+03, 1.18172609e+04,
        8.12262770e+03, 5.84791709e+03, 3.51158282e+03, 3.49968383e+03],
       [5.13914282e+03, 3.78003420e+03, 1.30460655e+03, 1.65997637e+03,
        3.54483216e+03, 3.41014569e+03, 1.54304662e+04, 4.04410186e+03,
        1.52825315e+04, 2.55247000e+03, 3.27053352e+03, 5.69796426e+03,
        0.00000000e+00, 5.53522292e+03, 1.61503960e+03, 1.65250704e+04,
        2.63863189e+03, 2.47803246e+02, 7.96548665e+03, 7.95201091e+03],
       [7.48057052e+03, 9.31518347e+03, 4.34081998e+03, 5.03819453e+03,
        8.25982951e+03, 6.82431572e+03, 1.18101747e+04, 6.60741886e+03,
        1.07227120e+04, 7.01426949e+03, 5.79457072e+03, 2.90256577e+03,
        5.53522292e+03, 0.00000000e+00, 7.06813323e+03, 1.34794954e+04,
        7.11632372e+03, 5.55034988e+03, 2.50134313e+03, 2.48887186e+03],
       [4.60365728e+03, 2.32800381e+03, 2.91941239e+03, 3.00745563e+03,
        2.20781502e+03, 2.88594371e+03, 1.64020562e+04, 3.72545776e+03,
        1.57489782e+04, 1.69998871e+03, 3.29636877e+03, 7.27266148e+03,
        1.61503960e+03, 7.06813323e+03, 0.00000000e+00, 1.68792959e+04,
        1.73090836e+03, 1.53661641e+03, 9.53633835e+03, 9.52307827e+03],
       [1.83753446e+04, 1.52238172e+04, 1.57997341e+04, 1.49297544e+04,
        1.77954113e+04, 1.96392564e+04, 1.67507494e+03, 1.94349063e+04,
        7.39422032e+03, 1.85092668e+04, 1.92717738e+04, 1.18172609e+04,
        1.65250704e+04, 1.34794954e+04, 1.68792959e+04, 0.00000000e+00,
        1.84907337e+04, 1.67726709e+04, 1.11309276e+04, 1.11407836e+04],
       [2.87585310e+03, 3.29270141e+03, 3.74119869e+03, 4.29278017e+03,
        1.14520933e+03, 1.20870378e+03, 1.80429372e+04, 2.08214705e+03,
        1.41231828e+04, 1.04901769e+02, 1.94460715e+03, 8.12262770e+03,
        2.63863189e+03, 7.11632372e+03, 1.73090836e+03, 1.84907337e+04,
        0.00000000e+00, 2.42082783e+03, 9.59952868e+03, 9.58782770e+03],
       [4.89188601e+03, 3.77792978e+03, 1.42338249e+03, 1.89304386e+03,
        3.36105731e+03, 3.16541873e+03, 1.56599317e+04, 3.79635060e+03,
        1.51118544e+04, 2.33190811e+03, 3.02716629e+03, 5.84791709e+03,
        2.47803246e+02, 5.55034988e+03, 1.53661641e+03, 1.67726709e+04,
        2.42082783e+03, 0.00000000e+00, 8.00468870e+03, 7.99135258e+03],
       [9.56172023e+03, 1.17222779e+04, 6.71110194e+03, 7.20001131e+03,
        1.07383397e+04, 9.20525753e+03, 9.50039762e+03, 8.85950223e+03,
        8.93150563e+03, 9.49876880e+03, 8.14274683e+03, 3.51158282e+03,
        7.96548665e+03, 2.50134313e+03, 9.53633835e+03, 1.11309276e+04,
        9.59952868e+03, 8.00468870e+03, 0.00000000e+00, 1.38462476e+01],
       [9.55443116e+03, 1.17086198e+04, 6.69745560e+03, 7.18616719e+03,
        1.07267806e+04, 9.19507278e+03, 9.50965010e+03, 8.85059619e+03,
        8.94458329e+03, 9.48703401e+03, 8.13280842e+03, 3.49968383e+03,
        7.95201091e+03, 2.48887186e+03, 9.52307827e+03, 1.11407836e+04,
        9.58782770e+03, 7.99135258e+03, 1.38462476e+01, 0.00000000e+00]])

In [18]:
## create the distance matrix with cities in the indexes
distance = pd.DataFrame(dist.pairwise(ct[['lat','lng']].to_numpy())*6373, columns = ct['ID'], index = ct['ID'])

In [19]:
## identify 'London' ID arrival
ct.loc[(ct['city'] == 'London') & (ct['iso3'] == 'GBR')]

      city      lat       lng iso3  population        ID
18  London  0.89897 -0.002225  GBR    10979000  LondonGB

In [20]:
## identify 'London_st' ID start
ct.loc[(ct['city'] == 'London_st')]

         city      lat       lng iso3  population           ID
19  London_st  0.89897  0.001265  GBR    10979000  London_stGB

In [21]:
## get starting line from distance matrix
distance.loc[['London_stGB']]

ID,TokyoJP,JakartaID,DelhiIN,MumbaiIN,ManilaPH,ShanghaiCN,São PauloBR,SeoulKR,Mexico CityMX,GuangzhouCN,BeijingCN,CairoEG,KolkātaIN,MoscowRU,BangkokTH,Buenos AiresAR,ShenzhenCN,DhakaBD,LondonGB,London_stGB
ID,,,,,,,,,,,,,,,,,,,,
London_stGB,9554.431161,11708.619812,6697.455601,7186.16719,10726.780625,9195.072779,9509.650099,8850.596186,8944.583295,9487.034011,8132.808416,3499.683835,7952.010912,2488.871859,9523.078272,11140.783559,9587.827696,7991.352582,13.846248,0.0

In [22]:
from pandas import DataFrame

In [23]:
#create the graph 
graph = pd.DataFrame(np.zeros(shape=(len(ct),len(ct))) , columns = ct['ID'], index = ct['ID'])

for i in distance :
    graph[i] = distance[i]*direction[i]
    
print(graph)

ID                  TokyoJP     JakartaID      DelhiIN     MumbaiIN  \
ID
TokyoJP            0.000000      0.000000     0.000000     0.000000
JakartaID       5787.903765      0.000000     0.000000     0.000000
DelhiIN         5835.248502   5011.267565     0.000000     0.000000
MumbaiIN        6736.368099   4662.287622  1166.997459     0.000000
ManilaPH        2997.194340      0.000000     0.000000     0.000000
ShanghaiCN      1762.022389      0.000000     0.000000     0.000000
São PauloBR        0.000000      0.000000     0.000000     0.000000
SeoulKR         1151.307887      0.000000     0.000000     0.000000
Mexico CityMX      0.000000      0.000000     0.000000     0.000000
GuangzhouCN     2903.800481      0.000000     0.000000     0.000000
BeijingCN       2094.455505      0.000000     0.000000     0.000000
CairoEG         9566.233300   8988.643865  4430.878464  4360.175097
KolkātaIN       5139.142818   3780.034204     0.000000     0.000000
MoscowRU        7480.570520   9315.183474  4340.819982  5038.194533
BangkokTH       4603.657275   2328.003809     0.000000     0.000000
Buenos AiresAR     0.000000      0.000000     0.000000     0.000000
ShenzhenCN      2875.853104      0.000000     0.000000     0.000000
DhakaBD         4891.886007   3777.929775     0.000000     0.000000
LondonGB           0.000000      0.000000     0.000000     0.000000
London_stGB     9554.431161  11708.619812  6697.455601  7186.167190

ID                  ManilaPH   ShanghaiCN   São PauloBR      SeoulKR  \
ID
TokyoJP             0.000000     0.000000  18539.985246     0.000000
JakartaID        2790.717691  4439.073727  15633.270814  5301.084998
DelhiIN          4755.337989  4245.899648  14435.543331  4686.015643
MumbaiIN         5135.012933  5042.317116  13770.532326  5609.664945
ManilaPH            0.000000  1843.853592  18383.444025  2625.115302
ShanghaiCN          0.000000     0.000000  18574.024002   875.628928
São PauloBR         0.000000     0.000000      0.000000     0.000000
SeoulKR             0.000000     0.000000  18346.808137     0.000000
Mexico CityMX       0.000000     0.000000   7434.356454     0.000000
GuangzhouCN      1248.624550  1207.102307  17969.010258  2074.465079
BeijingCN        2850.359766  1074.548887  17603.693097   955.203445
CairoEG          9179.548455  8359.079201  10223.802057  8488.214581
KolkātaIN        3544.832161  3410.145687  15430.466195  4044.101860
MoscowRU         8259.829515  6824.315717  11810.174661  6607.418859
BangkokTH        2207.815020  2885.943712  16402.056195  3725.457763
Buenos AiresAR      0.000000     0.000000   1675.074942     0.000000
ShenzhenCN       1145.209328  1208.703778  18042.937244  2082.147047
DhakaBD          3361.057310  3165.418730  15659.931690  3796.350596
LondonGB            0.000000     0.000000      0.000000     0.000000
London_stGB     10726.780625  9195.072779   9509.650099  8850.596186

ID              Mexico CityMX  GuangzhouCN    BeijingCN      CairoEG  \
ID
TokyoJP          11309.380364     0.000000     0.000000     0.000000
JakartaID        16850.822244  3337.523542  5222.603465     0.000000
DelhiIN          14657.705599  3643.361387  3775.416150     0.000000
MumbaiIN         15661.132639  4209.001394  4755.953582     0.000000
ManilaPH         14224.913173     0.000000     0.000000     0.000000
ShanghaiCN       12917.638799     0.000000     0.000000     0.000000
São PauloBR          0.000000     0.000000     0.000000     0.000000
SeoulKR          12052.659723     0.000000     0.000000     0.000000
Mexico CityMX        0.000000     0.000000     0.000000     0.000000
GuangzhouCN      14124.498662     0.000000  1889.146771     0.000000
BeijingCN        12462.623856     0.000000     0.000000     0.000000
CairoEG          12371.864145  8020.450078  7544.312312     0.000000
KolkātaIN        15282.531479  2552.469997  3270.533517     0.000000
MoscowRU         10722.711975  7014.269494  5794.570724     0.000000
BangkokTH        15748.978231  1699.988715  3296.368770     0.000000
Buenos AiresAR       0.000000     0.000000     0.000000     0.000000
ShenzhenCN       14123.182819     0.000000  1944.607150     0.000000
DhakaBD          15111.854413  2331.908114  3027.166288     0.000000
LondonGB             0.000000     0.000000     0.000000     0.000000
London_stGB       8944.583295  9487.034011  8132.808416  3499.683835

ID                KolkātaIN     MoscowRU    BangkokTH  Buenos AiresAR  \
ID
TokyoJP            0.000000     0.000000     0.000000    18375.344611
JakartaID          0.000000     0.000000     0.000000    15223.817165
DelhiIN         1304.606546     0.000000  2919.412392    15799.734123
MumbaiIN        1659.976374     0.000000  3007.455629    14929.754433
ManilaPH           0.000000     0.000000     0.000000    17795.411299
ShanghaiCN         0.000000     0.000000     0.000000    19639.256352
São PauloBR        0.000000     0.000000     0.000000        0.000000
SeoulKR            0.000000     0.000000     0.000000    19434.906275
Mexico CityMX      0.000000     0.000000     0.000000     7394.220315
GuangzhouCN        0.000000     0.000000     0.000000    18509.266783
BeijingCN          0.000000     0.000000     0.000000    19271.773784
CairoEG         5697.964257  2902.565775  7272.661485    11817.260885
KolkātaIN          0.000000     0.000000  1615.039600    16525.070407
MoscowRU        5535.222916     0.000000  7068.133232    13479.495433
BangkokTH          0.000000     0.000000     0.000000    16879.295914
Buenos AiresAR     0.000000     0.000000     0.000000        0.000000
ShenzhenCN         0.000000     0.000000     0.000000    18490.733715
DhakaBD            0.000000     0.000000  1536.616408    16772.670910
LondonGB           0.000000     0.000000     0.000000        0.000000
London_stGB     7952.010912  2488.871859  9523.078272    11140.783559

ID               ShenzhenCN      DhakaBD      LondonGB  London_stGB
ID
TokyoJP            0.000000     0.000000   9561.720229          0.0
JakartaID       3292.701406     0.000000  11722.277893          0.0
DelhiIN         3741.198686  1423.382495   6711.101944          0.0
MumbaiIN        4292.780170  1893.043863   7200.011313          0.0
ManilaPH           0.000000     0.000000  10738.339656          0.0
ShanghaiCN         0.000000     0.000000   9205.257531          0.0
São PauloBR        0.000000     0.000000   9500.397619          0.0
SeoulKR            0.000000     0.000000   8859.502225          0.0
Mexico CityMX      0.000000     0.000000   8931.505631          0.0
GuangzhouCN      104.901769     0.000000   9498.768799          0.0
BeijingCN          0.000000     0.000000   8142.746826          0.0
CairoEG         8122.627695  5847.917089   3511.582820          0.0
KolkātaIN       2638.631889   247.803246   7965.486648          0.0
MoscowRU        7116.323719  5550.349880   2501.343134          0.0
BangkokTH       1730.908362     0.000000   9536.338354          0.0
Buenos AiresAR     0.000000     0.000000  11130.927641          0.0
ShenzhenCN         0.000000     0.000000   9599.528680          0.0
DhakaBD         2420.827825     0.000000   8004.688703          0.0
LondonGB           0.000000     0.000000      0.000000          0.0
London_stGB     9587.827696  7991.352582     13.846248          0.0

In [24]:
graph.loc['London_stGB']['LondonGB'] = 0
print(graph)

ID                  TokyoJP     JakartaID      DelhiIN     MumbaiIN  \
ID
TokyoJP            0.000000      0.000000     0.000000     0.000000
JakartaID       5787.903765      0.000000     0.000000     0.000000
DelhiIN         5835.248502   5011.267565     0.000000     0.000000
MumbaiIN        6736.368099   4662.287622  1166.997459     0.000000
ManilaPH        2997.194340      0.000000     0.000000     0.000000
ShanghaiCN      1762.022389      0.000000     0.000000     0.000000
São PauloBR        0.000000      0.000000     0.000000     0.000000
SeoulKR         1151.307887      0.000000     0.000000     0.000000
Mexico CityMX      0.000000      0.000000     0.000000     0.000000
GuangzhouCN     2903.800481      0.000000     0.000000     0.000000
BeijingCN       2094.455505      0.000000     0.000000     0.000000
CairoEG         9566.233300   8988.643865  4430.878464  4360.175097
KolkātaIN       5139.142818   3780.034204     0.000000     0.000000
MoscowRU        7480.570520   9315.183474  4340.819982  5038.194533
BangkokTH       4603.657275   2328.003809     0.000000     0.000000
Buenos AiresAR     0.000000      0.000000     0.000000     0.000000
ShenzhenCN      2875.853104      0.000000     0.000000     0.000000
DhakaBD         4891.886007   3777.929775     0.000000     0.000000
LondonGB           0.000000      0.000000     0.000000     0.000000
London_stGB     9554.431161  11708.619812  6697.455601  7186.167190

ID                  ManilaPH   ShanghaiCN   São PauloBR      SeoulKR  \
ID
TokyoJP             0.000000     0.000000  18539.985246     0.000000
JakartaID        2790.717691  4439.073727  15633.270814  5301.084998
DelhiIN          4755.337989  4245.899648  14435.543331  4686.015643
MumbaiIN         5135.012933  5042.317116  13770.532326  5609.664945
ManilaPH            0.000000  1843.853592  18383.444025  2625.115302
ShanghaiCN          0.000000     0.000000  18574.024002   875.628928
São PauloBR         0.000000     0.000000      0.000000     0.000000
SeoulKR             0.000000     0.000000  18346.808137     0.000000
Mexico CityMX       0.000000     0.000000   7434.356454     0.000000
GuangzhouCN      1248.624550  1207.102307  17969.010258  2074.465079
BeijingCN        2850.359766  1074.548887  17603.693097   955.203445
CairoEG          9179.548455  8359.079201  10223.802057  8488.214581
KolkātaIN        3544.832161  3410.145687  15430.466195  4044.101860
MoscowRU         8259.829515  6824.315717  11810.174661  6607.418859
BangkokTH        2207.815020  2885.943712  16402.056195  3725.457763
Buenos AiresAR      0.000000     0.000000   1675.074942     0.000000
ShenzhenCN       1145.209328  1208.703778  18042.937244  2082.147047
DhakaBD          3361.057310  3165.418730  15659.931690  3796.350596
LondonGB            0.000000     0.000000      0.000000     0.000000
London_stGB     10726.780625  9195.072779   9509.650099  8850.596186

ID              Mexico CityMX  GuangzhouCN    BeijingCN      CairoEG  \
ID
TokyoJP          11309.380364     0.000000     0.000000     0.000000
JakartaID        16850.822244  3337.523542  5222.603465     0.000000
DelhiIN          14657.705599  3643.361387  3775.416150     0.000000
MumbaiIN         15661.132639  4209.001394  4755.953582     0.000000
ManilaPH         14224.913173     0.000000     0.000000     0.000000
ShanghaiCN       12917.638799     0.000000     0.000000     0.000000
São PauloBR          0.000000     0.000000     0.000000     0.000000
SeoulKR          12052.659723     0.000000     0.000000     0.000000
Mexico CityMX        0.000000     0.000000     0.000000     0.000000
GuangzhouCN      14124.498662     0.000000  1889.146771     0.000000
BeijingCN        12462.623856     0.000000     0.000000     0.000000
CairoEG          12371.864145  8020.450078  7544.312312     0.000000
KolkātaIN        15282.531479  2552.469997  3270.533517     0.000000
MoscowRU         10722.711975  7014.269494  5794.570724     0.000000
BangkokTH        15748.978231  1699.988715  3296.368770     0.000000
Buenos AiresAR       0.000000     0.000000     0.000000     0.000000
ShenzhenCN       14123.182819     0.000000  1944.607150     0.000000
DhakaBD          15111.854413  2331.908114  3027.166288     0.000000
LondonGB             0.000000     0.000000     0.000000     0.000000
London_stGB       8944.583295  9487.034011  8132.808416  3499.683835

ID                KolkātaIN     MoscowRU    BangkokTH  Buenos AiresAR  \
ID
TokyoJP            0.000000     0.000000     0.000000    18375.344611
JakartaID          0.000000     0.000000     0.000000    15223.817165
DelhiIN         1304.606546     0.000000  2919.412392    15799.734123
MumbaiIN        1659.976374     0.000000  3007.455629    14929.754433
ManilaPH           0.000000     0.000000     0.000000    17795.411299
ShanghaiCN         0.000000     0.000000     0.000000    19639.256352
São PauloBR        0.000000     0.000000     0.000000        0.000000
SeoulKR            0.000000     0.000000     0.000000    19434.906275
Mexico CityMX      0.000000     0.000000     0.000000     7394.220315
GuangzhouCN        0.000000     0.000000     0.000000    18509.266783
BeijingCN          0.000000     0.000000     0.000000    19271.773784
CairoEG         5697.964257  2902.565775  7272.661485    11817.260885
KolkātaIN          0.000000     0.000000  1615.039600    16525.070407
MoscowRU        5535.222916     0.000000  7068.133232    13479.495433
BangkokTH          0.000000     0.000000     0.000000    16879.295914
Buenos AiresAR     0.000000     0.000000     0.000000        0.000000
ShenzhenCN         0.000000     0.000000     0.000000    18490.733715
DhakaBD            0.000000     0.000000  1536.616408    16772.670910
LondonGB           0.000000     0.000000     0.000000        0.000000
London_stGB     7952.010912  2488.871859  9523.078272    11140.783559

ID               ShenzhenCN      DhakaBD      LondonGB  London_stGB
ID
TokyoJP            0.000000     0.000000   9561.720229          0.0
JakartaID       3292.701406     0.000000  11722.277893          0.0
DelhiIN         3741.198686  1423.382495   6711.101944          0.0
MumbaiIN        4292.780170  1893.043863   7200.011313          0.0
ManilaPH           0.000000     0.000000  10738.339656          0.0
ShanghaiCN         0.000000     0.000000   9205.257531          0.0
São PauloBR        0.000000     0.000000   9500.397619          0.0
SeoulKR            0.000000     0.000000   8859.502225          0.0
Mexico CityMX      0.000000     0.000000   8931.505631          0.0
GuangzhouCN      104.901769     0.000000   9498.768799          0.0
BeijingCN          0.000000     0.000000   8142.746826          0.0
CairoEG         8122.627695  5847.917089   3511.582820          0.0
KolkātaIN       2638.631889   247.803246   7965.486648          0.0
MoscowRU        7116.323719  5550.349880   2501.343134          0.0
BangkokTH       1730.908362     0.000000   9536.338354          0.0
Buenos AiresAR     0.000000     0.000000  11130.927641          0.0
ShenzhenCN         0.000000     0.000000   9599.528680          0.0
DhakaBD         2420.827825     0.000000   8004.688703          0.0
LondonGB           0.000000     0.000000      0.000000          0.0
London_stGB     9587.827696  7991.352582      0.000000          0.0

In [25]:
graph = graph.T
print(graph)

ID                   TokyoJP     JakartaID       DelhiIN      MumbaiIN  \
ID
TokyoJP             0.000000   5787.903765   5835.248502   6736.368099
JakartaID           0.000000      0.000000   5011.267565   4662.287622
DelhiIN             0.000000      0.000000      0.000000   1166.997459
MumbaiIN            0.000000      0.000000      0.000000      0.000000
ManilaPH            0.000000   2790.717691   4755.337989   5135.012933
ShanghaiCN          0.000000   4439.073727   4245.899648   5042.317116
São PauloBR     18539.985246  15633.270814  14435.543331  13770.532326
SeoulKR             0.000000   5301.084998   4686.015643   5609.664945
Mexico CityMX   11309.380364  16850.822244  14657.705599  15661.132639
GuangzhouCN         0.000000   3337.523542   3643.361387   4209.001394
BeijingCN           0.000000   5222.603465   3775.416150   4755.953582
CairoEG             0.000000      0.000000      0.000000      0.000000
KolkātaIN           0.000000      0.000000   1304.606546   1659.976374
MoscowRU            0.000000      0.000000      0.000000      0.000000
BangkokTH           0.000000      0.000000   2919.412392   3007.455629
Buenos AiresAR  18375.344611  15223.817165  15799.734123  14929.754433
ShenzhenCN          0.000000   3292.701406   3741.198686   4292.780170
DhakaBD             0.000000      0.000000   1423.382495   1893.043863
LondonGB         9561.720229  11722.277893   6711.101944   7200.011313
London_stGB         0.000000      0.000000      0.000000      0.000000

ID                  ManilaPH    ShanghaiCN  São PauloBR       SeoulKR  \
ID
TokyoJP          2997.194340   1762.022389     0.000000   1151.307887
JakartaID           0.000000      0.000000     0.000000      0.000000
DelhiIN             0.000000      0.000000     0.000000      0.000000
MumbaiIN            0.000000      0.000000     0.000000      0.000000
ManilaPH            0.000000      0.000000     0.000000      0.000000
ShanghaiCN       1843.853592      0.000000     0.000000      0.000000
São PauloBR     18383.444025  18574.024002     0.000000  18346.808137
SeoulKR          2625.115302    875.628928     0.000000      0.000000
Mexico CityMX   14224.913173  12917.638799     0.000000  12052.659723
GuangzhouCN         0.000000      0.000000     0.000000      0.000000
BeijingCN           0.000000      0.000000     0.000000      0.000000
CairoEG             0.000000      0.000000     0.000000      0.000000
KolkātaIN           0.000000      0.000000     0.000000      0.000000
MoscowRU            0.000000      0.000000     0.000000      0.000000
BangkokTH           0.000000      0.000000     0.000000      0.000000
Buenos AiresAR  17795.411299  19639.256352     0.000000  19434.906275
ShenzhenCN          0.000000      0.000000     0.000000      0.000000
DhakaBD             0.000000      0.000000     0.000000      0.000000
LondonGB        10738.339656   9205.257531  9500.397619   8859.502225
London_stGB         0.000000      0.000000     0.000000      0.000000

ID              Mexico CityMX   GuangzhouCN     BeijingCN       CairoEG  \
ID
TokyoJP              0.000000   2903.800481   2094.455505   9566.233300
JakartaID            0.000000      0.000000      0.000000   8988.643865
DelhiIN              0.000000      0.000000      0.000000   4430.878464
MumbaiIN             0.000000      0.000000      0.000000   4360.175097
ManilaPH             0.000000   1248.624550   2850.359766   9179.548455
ShanghaiCN           0.000000   1207.102307   1074.548887   8359.079201
São PauloBR       7434.356454  17969.010258  17603.693097  10223.802057
SeoulKR              0.000000   2074.465079    955.203445   8488.214581
Mexico CityMX        0.000000  14124.498662  12462.623856  12371.864145
GuangzhouCN          0.000000      0.000000      0.000000   8020.450078
BeijingCN            0.000000   1889.146771      0.000000   7544.312312
CairoEG              0.000000      0.000000      0.000000      0.000000
KolkātaIN            0.000000      0.000000      0.000000   5697.964257
MoscowRU             0.000000      0.000000      0.000000   2902.565775
BangkokTH            0.000000      0.000000      0.000000   7272.661485
Buenos AiresAR    7394.220315  18509.266783  19271.773784  11817.260885
ShenzhenCN           0.000000    104.901769      0.000000   8122.627695
DhakaBD              0.000000      0.000000      0.000000   5847.917089
LondonGB          8931.505631   9498.768799   8142.746826   3511.582820
London_stGB          0.000000      0.000000      0.000000      0.000000

ID                 KolkātaIN      MoscowRU     BangkokTH  Buenos AiresAR  \
ID
TokyoJP          5139.142818   7480.570520   4603.657275        0.000000
JakartaID        3780.034204   9315.183474   2328.003809        0.000000
DelhiIN             0.000000   4340.819982      0.000000        0.000000
MumbaiIN            0.000000   5038.194533      0.000000        0.000000
ManilaPH         3544.832161   8259.829515   2207.815020        0.000000
ShanghaiCN       3410.145687   6824.315717   2885.943712        0.000000
São PauloBR     15430.466195  11810.174661  16402.056195     1675.074942
SeoulKR          4044.101860   6607.418859   3725.457763        0.000000
Mexico CityMX   15282.531479  10722.711975  15748.978231        0.000000
GuangzhouCN      2552.469997   7014.269494   1699.988715        0.000000
BeijingCN        3270.533517   5794.570724   3296.368770        0.000000
CairoEG             0.000000      0.000000      0.000000        0.000000
KolkātaIN           0.000000   5535.222916      0.000000        0.000000
MoscowRU            0.000000      0.000000      0.000000        0.000000
BangkokTH        1615.039600   7068.133232      0.000000        0.000000
Buenos AiresAR  16525.070407  13479.495433  16879.295914        0.000000
ShenzhenCN       2638.631889   7116.323719   1730.908362        0.000000
DhakaBD           247.803246   5550.349880      0.000000        0.000000
LondonGB         7965.486648   2501.343134   9536.338354    11130.927641
London_stGB         0.000000      0.000000      0.000000        0.000000

ID                ShenzhenCN       DhakaBD  LondonGB   London_stGB
ID
TokyoJP          2875.853104   4891.886007       0.0   9554.431161
JakartaID           0.000000   3777.929775       0.0  11708.619812
DelhiIN             0.000000      0.000000       0.0   6697.455601
MumbaiIN            0.000000      0.000000       0.0   7186.167190
ManilaPH         1145.209328   3361.057310       0.0  10726.780625
ShanghaiCN       1208.703778   3165.418730       0.0   9195.072779
São PauloBR     18042.937244  15659.931690       0.0   9509.650099
SeoulKR          2082.147047   3796.350596       0.0   8850.596186
Mexico CityMX   14123.182819  15111.854413       0.0   8944.583295
GuangzhouCN         0.000000   2331.908114       0.0   9487.034011
BeijingCN        1944.607150   3027.166288       0.0   8132.808416
CairoEG             0.000000      0.000000       0.0   3499.683835
KolkātaIN           0.000000      0.000000       0.0   7952.010912
MoscowRU            0.000000      0.000000       0.0   2488.871859
BangkokTH           0.000000   1536.616408       0.0   9523.078272
Buenos AiresAR  18490.733715  16772.670910       0.0  11140.783559
ShenzhenCN          0.000000   2420.827825       0.0   9587.827696
DhakaBD             0.000000      0.000000       0.0   7991.352582
LondonGB         9599.528680   8004.688703       0.0      0.000000
London_stGB         0.000000      0.000000       0.0      0.000000

In [26]:
dis = graph.replace(0, 0)
dis

ID,TokyoJP,JakartaID,DelhiIN,MumbaiIN,ManilaPH,ShanghaiCN,São PauloBR,SeoulKR,Mexico CityMX,GuangzhouCN,BeijingCN,CairoEG,KolkātaIN,MoscowRU,BangkokTH,Buenos AiresAR,ShenzhenCN,DhakaBD,LondonGB,London_stGB
ID,,,,,,,,,,,,,,,,,,,,
TokyoJP,0.000000,5787.903765,5835.248502,6736.368099,2997.194340,1762.022389,0.000000,1151.307887,0.000000,2903.800481,2094.455505,9566.233300,5139.142818,7480.570520,4603.657275,0.000000,2875.853104,4891.886007,0.0,9554.431161
JakartaID,0.000000,0.000000,5011.267565,4662.287622,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8988.643865,3780.034204,9315.183474,2328.003809,0.000000,0.000000,3777.929775,0.0,11708.619812
DelhiIN,0.000000,0.000000,0.000000,1166.997459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4430.878464,0.000000,4340.819982,0.000000,0.000000,0.000000,0.000000,0.0,6697.455601
MumbaiIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4360.175097,0.000000,5038.194533,0.000000,0.000000,0.000000,0.000000,0.0,7186.167190
ManilaPH,0.000000,2790.717691,4755.337989,5135.012933,0.000000,0.000000,0.000000,0.000000,0.000000,1248.624550,2850.359766,9179.548455,3544.832161,8259.829515,2207.815020,0.000000,1145.209328,3361.057310,0.0,10726.780625
ShanghaiCN,0.000000,4439.073727,4245.899648,5042.317116,1843.853592,0.000000,0.000000,0.000000,0.000000,1207.102307,1074.548887,8359.079201,3410.145687,6824.315717,2885.943712,0.000000,1208.703778,3165.418730,0.0,9195.072779
São PauloBR,18539.985246,15633.270814,14435.543331,13770.532326,18383.444025,18574.024002,0.000000,18346.808137,7434.356454,17969.010258,17603.693097,10223.802057,15430.466195,11810.174661,16402.056195,1675.074942,18042.937244,15659.931690,0.0,9509.650099
SeoulKR,0.000000,5301.084998,4686.015643,5609.664945,2625.115302,875.628928,0.000000,0.000000,0.000000,2074.465079,955.203445,8488.214581,4044.101860,6607.418859,3725.457763,0.000000,2082.147047,3796.350596,0.0,8850.596186
Mexico CityMX,11309.380364,16850.822244,14657.705599,15661.132639,14224.913173,12917.638799,0.000000,12052.659723,0.000000,14124.498662,12462.623856,12371.864145,15282.531479,10722.711975,15748.978231,0.000000,14123.182819,15111.854413,0.0,8944.583295
GuangzhouCN,0.000000,3337.523542,3643.361387,4209.001394,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8020.450078,2552.469997,7014.269494,1699.988715,0.000000,0.000000,2331.908114,0.0,9487.034011
BeijingCN,0.000000,5222.603465,3775.416150,4755.953582,0.000000,0.000000,0.000000,0.000000,0.000000,1889.146771,0.000000,7544.312312,3270.533517,5794.570724,3296.368770,0.000000,1944.607150,3027.166288,0.0,8132.808416
CairoEG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,3499.683835
KolkātaIN,0.000000,0.000000,1304.606546,1659.976374,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5697.964257,0.000000,5535.222916,0.000000,0.000000,0.000000,0.000000,0.0,7952.010912
MoscowRU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2902.565775,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2488.871859
BangkokTH,0.000000,0.000000,2919.412392,3007.455629,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7272.661485,1615.039600,7068.133232,0.000000,0.000000,0.000000,1536.616408,0.0,9523.078272
Buenos AiresAR,18375.344611,15223.817165,15799.734123,14929.754433,17795.411299,19639.256352,0.000000,19434.906275,7394.220315,18509.266783,19271.773784,11817.260885,16525.070407,13479.495433,16879.295914,0.000000,18490.733715,16772.670910,0.0,11140.783559
ShenzhenCN,0.000000,3292.701406,3741.198686,4292.780170,0.000000,0.000000,0.000000,0.000000,0.000000,104.901769,0.000000,8122.627695,2638.631889,7116.323719,1730.908362,0.000000,0.000000,2420.827825,0.0,9587.827696
DhakaBD,0.000000,0.000000,1423.382495,1893.043863,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5847.917089,247.803246,5550.349880,0.000000,0.000000,0.000000,0.000000,0.0,7991.352582
LondonGB,9561.720229,11722.277893,6711.101944,7200.011313,10738.339656,9205.257531,9500.397619,8859.502225,8931.505631,9498.768799,8142.746826,3511.582820,7965.486648,2501.343134,9536.338354,11130.927641,9599.528680,8004.688703,0.0,0.000000
London_stGB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [27]:
## popolare per criteri (più vicino +2, secondo più vicino +4, terzo più vicino +8, il resto 'no go')
dis = graph.replace(0, 0)
dis = dis.replace(dis.apply(lambda x: x[x > 0].min(axis=0)), 2)
dis = dis.replace(dis.apply(lambda x: x[x > 2].min(axis=0)), 4)
dis = dis.replace(dis.apply(lambda x: x[x > 4].min(axis=0)), 8)
dis
#dis = dis.replace(dis.apply(lambda x: x[x > 8]), 'no go')

ID,TokyoJP,JakartaID,DelhiIN,MumbaiIN,ManilaPH,ShanghaiCN,São PauloBR,SeoulKR,Mexico CityMX,GuangzhouCN,BeijingCN,CairoEG,KolkātaIN,MoscowRU,BangkokTH,Buenos AiresAR,ShenzhenCN,DhakaBD,LondonGB,London_stGB
ID,,,,,,,,,,,,,,,,,,,,
TokyoJP,0.000000,5787.903765,5835.248502,6736.368099,8.000000,4.000000,0.0,2.000000,0.0,2903.800481,8.000000,9566.233300,5139.142818,7480.570520,4603.657275,0.0,2875.853104,4891.886007,0.0,9554.431161
JakartaID,0.000000,0.000000,5011.267565,4662.287622,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,8988.643865,3780.034204,9315.183474,2328.003809,0.0,0.000000,3777.929775,0.0,11708.619812
DelhiIN,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,4430.878464,0.000000,4.000000,0.000000,0.0,0.000000,0.000000,0.0,8.000000
MumbaiIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,8.000000,0.000000,8.000000,0.000000,0.0,0.000000,0.000000,0.0,7186.167190
ManilaPH,0.000000,2.000000,4755.337989,5135.012933,0.000000,0.000000,0.0,0.000000,0.0,8.000000,2850.359766,9179.548455,3544.832161,8259.829515,8.000000,0.0,2.000000,3361.057310,0.0,10726.780625
ShanghaiCN,0.000000,4439.073727,4245.899648,5042.317116,2.000000,0.000000,0.0,0.000000,0.0,4.000000,4.000000,8359.079201,3410.145687,6824.315717,2885.943712,0.0,4.000000,3165.418730,0.0,9195.072779
São PauloBR,18539.985246,15633.270814,14435.543331,13770.532326,18383.444025,18574.024002,0.0,18346.808137,4.0,17969.010258,17603.693097,10223.802057,15430.466195,11810.174661,16402.056195,2.0,18042.937244,15659.931690,0.0,9509.650099
SeoulKR,0.000000,5301.084998,4686.015643,5609.664945,4.000000,2.000000,0.0,0.000000,0.0,2074.465079,2.000000,8488.214581,4044.101860,6607.418859,3725.457763,0.0,2082.147047,3796.350596,0.0,8850.596186
Mexico CityMX,4.000000,16850.822244,14657.705599,15661.132639,14224.913173,12917.638799,0.0,8.000000,0.0,14124.498662,12462.623856,12371.864145,15282.531479,10722.711975,15748.978231,0.0,14123.182819,15111.854413,0.0,8944.583295
GuangzhouCN,0.000000,8.000000,3643.361387,4209.001394,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,8020.450078,8.000000,7014.269494,2.000000,0.0,0.000000,4.000000,0.0,9487.034011
BeijingCN,0.000000,5222.603465,3775.416150,4755.953582,0.000000,0.000000,0.0,0.000000,0.0,1889.146771,0.000000,7544.312312,3270.533517,5794.570724,3296.368770,0.0,8.000000,3027.166288,0.0,8132.808416
CairoEG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,4.000000
KolkātaIN,0.000000,0.000000,2.000000,4.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,5697.964257,0.000000,5535.222916,0.000000,0.0,0.000000,0.000000,0.0,7952.010912
MoscowRU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,2.000000
BangkokTH,0.000000,0.000000,8.000000,3007.455629,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,7272.661485,4.000000,7068.133232,0.000000,0.0,0.000000,2.000000,0.0,9523.078272
Buenos AiresAR,8.000000,15223.817165,15799.734123,14929.754433,17795.411299,19639.256352,0.0,19434.906275,2.0,18509.266783,19271.773784,11817.260885,16525.070407,13479.495433,16879.295914,0.0,18490.733715,16772.670910,0.0,11140.783559
ShenzhenCN,0.000000,4.000000,3741.198686,4292.780170,0.000000,0.000000,0.0,0.000000,0.0,2.000000,0.000000,8122.627695,2638.631889,7116.323719,4.000000,0.0,0.000000,8.000000,0.0,9587.827696
DhakaBD,0.000000,0.000000,4.000000,8.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,5847.917089,2.000000,5550.349880,0.000000,0.0,0.000000,0.000000,0.0,7991.352582
LondonGB,2.000000,11722.277893,6711.101944,7200.011313,10738.339656,8.000000,2.0,4.000000,8.0,9498.768799,8142.746826,4.000000,7965.486648,2.000000,9536.338354,4.0,9599.528680,8004.688703,0.0,0.000000
London_stGB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000

In [28]:
#parte messa solo perchè l'utima riga sopra non mi va 
dis = dis.where((dis <= 8), 0) 
dis

ID,TokyoJP,JakartaID,DelhiIN,MumbaiIN,ManilaPH,ShanghaiCN,São PauloBR,SeoulKR,Mexico CityMX,GuangzhouCN,BeijingCN,CairoEG,KolkātaIN,MoscowRU,BangkokTH,Buenos AiresAR,ShenzhenCN,DhakaBD,LondonGB,London_stGB
ID,,,,,,,,,,,,,,,,,,,,
TokyoJP,0.0,0.0,0.0,0.0,8.0,4.0,0.0,2.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
JakartaID,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DelhiIN,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,8.0
MumbaiIN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
ManilaPH,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,8.0,0.0,2.0,0.0,0.0,0.0
ShanghaiCN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
São PauloBR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
SeoulKR,0.0,0.0,0.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Mexico CityMX,4.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GuangzhouCN,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,2.0,0.0,0.0,4.0,0.0,0.0
BeijingCN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0
CairoEG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
KolkātaIN,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MoscowRU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
BangkokTH,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
Buenos AiresAR,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShenzhenCN,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,8.0,0.0,0.0
DhakaBD,0.0,0.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LondonGB,2.0,0.0,0.0,0.0,0.0,8.0,2.0,4.0,8.0,0.0,0.0,4.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0
London_stGB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
print(dis)

ID              TokyoJP  JakartaID  DelhiIN  MumbaiIN  ManilaPH  ShanghaiCN  \
ID
TokyoJP             0.0        0.0      0.0       0.0       8.0         4.0
JakartaID           0.0        0.0      0.0       0.0       0.0         0.0
DelhiIN             0.0        0.0      0.0       2.0       0.0         0.0
MumbaiIN            0.0        0.0      0.0       0.0       0.0         0.0
ManilaPH            0.0        2.0      0.0       0.0       0.0         0.0
ShanghaiCN          0.0        0.0      0.0       0.0       2.0         0.0
São PauloBR         0.0        0.0      0.0       0.0       0.0         0.0
SeoulKR             0.0        0.0      0.0       0.0       4.0         2.0
Mexico CityMX       4.0        0.0      0.0       0.0       0.0         0.0
GuangzhouCN         0.0        8.0      0.0       0.0       0.0         0.0
BeijingCN           0.0        0.0      0.0       0.0       0.0         0.0
CairoEG             0.0        0.0      0.0       0.0       0.0         0.0
KolkātaIN           0.0        0.0      2.0       4.0       0.0         0.0
MoscowRU            0.0        0.0      0.0       0.0       0.0         0.0
BangkokTH           0.0        0.0      8.0       0.0       0.0         0.0
Buenos AiresAR      8.0        0.0      0.0       0.0       0.0         0.0
ShenzhenCN          0.0        4.0      0.0       0.0       0.0         0.0
DhakaBD             0.0        0.0      4.0       8.0       0.0         0.0
LondonGB            2.0        0.0      0.0       0.0       0.0         8.0
London_stGB         0.0        0.0      0.0       0.0       0.0         0.0

ID              São PauloBR  SeoulKR  Mexico CityMX  GuangzhouCN  BeijingCN  \
ID
TokyoJP                 0.0      2.0            0.0          0.0        8.0
JakartaID               0.0      0.0            0.0          0.0        0.0
DelhiIN                 0.0      0.0            0.0          0.0        0.0
MumbaiIN                0.0      0.0            0.0          0.0        0.0
ManilaPH                0.0      0.0            0.0          8.0        0.0
ShanghaiCN              0.0      0.0            0.0          4.0        4.0
São PauloBR             0.0      0.0            4.0          0.0        0.0
SeoulKR                 0.0      0.0            0.0          0.0        2.0
Mexico CityMX           0.0      8.0            0.0          0.0        0.0
GuangzhouCN             0.0      0.0            0.0          0.0        0.0
BeijingCN               0.0      0.0            0.0          0.0        0.0
CairoEG                 0.0      0.0            0.0          0.0        0.0
KolkātaIN               0.0      0.0            0.0          0.0        0.0
MoscowRU                0.0      0.0            0.0          0.0        0.0
BangkokTH               0.0      0.0            0.0          0.0        0.0
Buenos AiresAR          0.0      0.0            2.0          0.0        0.0
ShenzhenCN              0.0      0.0            0.0          2.0        0.0
DhakaBD                 0.0      0.0            0.0          0.0        0.0
LondonGB                2.0      4.0            8.0          0.0        0.0
London_stGB             0.0      0.0            0.0          0.0        0.0

ID              CairoEG  KolkātaIN  MoscowRU  BangkokTH  Buenos AiresAR  \
ID
TokyoJP             0.0        0.0       0.0        0.0             0.0
JakartaID           0.0        0.0       0.0        0.0             0.0
DelhiIN             0.0        0.0       4.0        0.0             0.0
MumbaiIN            8.0        0.0       8.0        0.0             0.0
ManilaPH            0.0        0.0       0.0        8.0             0.0
ShanghaiCN          0.0        0.0       0.0        0.0             0.0
São PauloBR         0.0        0.0       0.0        0.0             2.0
SeoulKR             0.0        0.0       0.0        0.0             0.0
Mexico CityMX       0.0        0.0       0.0        0.0             0.0
GuangzhouCN         0.0        8.0       0.0        2.0             0.0
BeijingCN           0.0        0.0       0.0        0.0             0.0
CairoEG             0.0        0.0       0.0        0.0             0.0
KolkātaIN           0.0        0.0       0.0        0.0             0.0
MoscowRU            2.0        0.0       0.0        0.0             0.0
BangkokTH           0.0        4.0       0.0        0.0             0.0
Buenos AiresAR      0.0        0.0       0.0        0.0             0.0
ShenzhenCN          0.0        0.0       0.0        4.0             0.0
DhakaBD             0.0        2.0       0.0        0.0             0.0
LondonGB            4.0        0.0       2.0        0.0             4.0
London_stGB         0.0        0.0       0.0        0.0             0.0

ID              ShenzhenCN  DhakaBD  LondonGB  London_stGB
ID
TokyoJP                0.0      0.0       0.0          0.0
JakartaID              0.0      0.0       0.0          0.0
DelhiIN                0.0      0.0       0.0          8.0
MumbaiIN               0.0      0.0       0.0          0.0
ManilaPH               2.0      0.0       0.0          0.0
ShanghaiCN             4.0      0.0       0.0          0.0
São PauloBR            0.0      0.0       0.0          0.0
SeoulKR                0.0      0.0       0.0          0.0
Mexico CityMX          0.0      0.0       0.0          0.0
GuangzhouCN            0.0      4.0       0.0          0.0
BeijingCN              8.0      0.0       0.0          0.0
CairoEG                0.0      0.0       0.0          4.0
KolkātaIN              0.0      0.0       0.0          0.0
MoscowRU               0.0      0.0       0.0          2.0
BangkokTH              0.0      2.0       0.0          0.0
Buenos AiresAR         0.0      0.0       0.0          0.0
ShenzhenCN             0.0      8.0       0.0          0.0
DhakaBD                0.0      0.0       0.0          0.0
LondonGB               0.0      0.0       0.0          0.0
London_stGB            0.0      0.0       0.0          0.0

In [30]:
for i in dis :
    graph[i] = (dis[i] + same_state[i] + pop) * dis[i] / dis[i]
    
graph

ID,TokyoJP,JakartaID,DelhiIN,MumbaiIN,ManilaPH,ShanghaiCN,São PauloBR,SeoulKR,Mexico CityMX,GuangzhouCN,BeijingCN,CairoEG,KolkātaIN,MoscowRU,BangkokTH,Buenos AiresAR,ShenzhenCN,DhakaBD,LondonGB,London_stGB
ID,,,,,,,,,,,,,,,,,,,,
TokyoJP,NaN,NaN,NaN,NaN,12.0,8.0,NaN,6.0,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JakartaID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DelhiIN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,12.0
MumbaiIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN
ManilaPH,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,12.0,NaN,6.0,NaN,NaN,NaN
ShanghaiCN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
São PauloBR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN
SeoulKR,NaN,NaN,NaN,NaN,8.0,6.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mexico CityMX,8.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GuangzhouCN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,6.0,NaN,NaN,8.0,NaN,NaN
BeijingCN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN
CairoEG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
KolkātaIN,NaN,NaN,4.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MoscowRU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
BangkokTH,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN
Buenos AiresAR,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ShenzhenCN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,12.0,NaN,NaN
DhakaBD,NaN,NaN,8.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LondonGB,6.0,NaN,NaN,NaN,NaN,12.0,6.0,8.0,12.0,NaN,NaN,8.0,NaN,6.0,NaN,8.0,NaN,NaN,NaN,NaN
London_stGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
print(graph)

ID              TokyoJP  JakartaID  DelhiIN  MumbaiIN  ManilaPH  ShanghaiCN  \
ID
TokyoJP             NaN        NaN      NaN       NaN      12.0         8.0
JakartaID           NaN        NaN      NaN       NaN       NaN         NaN
DelhiIN             NaN        NaN      NaN       4.0       NaN         NaN
MumbaiIN            NaN        NaN      NaN       NaN       NaN         NaN
ManilaPH            NaN        6.0      NaN       NaN       NaN         NaN
ShanghaiCN          NaN        NaN      NaN       NaN       6.0         NaN
São PauloBR         NaN        NaN      NaN       NaN       NaN         NaN
SeoulKR             NaN        NaN      NaN       NaN       8.0         6.0
Mexico CityMX       8.0        NaN      NaN       NaN       NaN         NaN
GuangzhouCN         NaN       12.0      NaN       NaN       NaN         NaN
BeijingCN           NaN        NaN      NaN       NaN       NaN         NaN
CairoEG             NaN        NaN      NaN       NaN       NaN         NaN
KolkātaIN           NaN        NaN      4.0       6.0       NaN         NaN
MoscowRU            NaN        NaN      NaN       NaN       NaN         NaN
BangkokTH           NaN        NaN     12.0       NaN       NaN         NaN
Buenos AiresAR     12.0        NaN      NaN       NaN       NaN         NaN
ShenzhenCN          NaN        8.0      NaN       NaN       NaN         NaN
DhakaBD             NaN        NaN      8.0      12.0       NaN         NaN
LondonGB            6.0        NaN      NaN       NaN       NaN        12.0
London_stGB         NaN        NaN      NaN       NaN       NaN         NaN

ID              São PauloBR  SeoulKR  Mexico CityMX  GuangzhouCN  BeijingCN  \
ID
TokyoJP                 NaN      6.0            NaN          NaN       12.0
JakartaID               NaN      NaN            NaN          NaN        NaN
DelhiIN                 NaN      NaN            NaN          NaN        NaN
MumbaiIN                NaN      NaN            NaN          NaN        NaN
ManilaPH                NaN      NaN            NaN         12.0        NaN
ShanghaiCN              NaN      NaN            NaN          6.0        6.0
São PauloBR             NaN      NaN            8.0          NaN        NaN
SeoulKR                 NaN      NaN            NaN          NaN        6.0
Mexico CityMX           NaN     12.0            NaN          NaN        NaN
GuangzhouCN             NaN      NaN            NaN          NaN        NaN
BeijingCN               NaN      NaN            NaN          NaN        NaN
CairoEG                 NaN      NaN            NaN          NaN        NaN
KolkātaIN               NaN      NaN            NaN          NaN        NaN
MoscowRU                NaN      NaN            NaN          NaN        NaN
BangkokTH               NaN      NaN            NaN          NaN        NaN
Buenos AiresAR          NaN      NaN            6.0          NaN        NaN
ShenzhenCN              NaN      NaN            NaN          4.0        NaN
DhakaBD                 NaN      NaN            NaN          NaN        NaN
LondonGB                6.0      8.0           12.0          NaN        NaN
London_stGB             NaN      NaN            NaN          NaN        NaN

ID              CairoEG  KolkātaIN  MoscowRU  BangkokTH  Buenos AiresAR  \
ID
TokyoJP             NaN        NaN       NaN        NaN             NaN
JakartaID           NaN        NaN       NaN        NaN             NaN
DelhiIN             NaN        NaN       8.0        NaN             NaN
MumbaiIN           12.0        NaN      12.0        NaN             NaN
ManilaPH            NaN        NaN       NaN       12.0             NaN
ShanghaiCN          NaN        NaN       NaN        NaN             NaN
São PauloBR         NaN        NaN       NaN        NaN             6.0
SeoulKR             NaN        NaN       NaN        NaN             NaN
Mexico CityMX       NaN        NaN       NaN        NaN             NaN
GuangzhouCN         NaN       12.0       NaN        6.0             NaN
BeijingCN           NaN        NaN       NaN        NaN             NaN
CairoEG             NaN        NaN       NaN        NaN             NaN
KolkātaIN           NaN        NaN       NaN        NaN             NaN
MoscowRU            6.0        NaN       NaN        NaN             NaN
BangkokTH           NaN        8.0       NaN        NaN             NaN
Buenos AiresAR      NaN        NaN       NaN        NaN             NaN
ShenzhenCN          NaN        NaN       NaN        8.0             NaN
DhakaBD             NaN        6.0       NaN        NaN             NaN
LondonGB            8.0        NaN       6.0        NaN             8.0
London_stGB         NaN        NaN       NaN        NaN             NaN

ID              ShenzhenCN  DhakaBD  LondonGB  London_stGB
ID
TokyoJP                NaN      NaN       NaN          NaN
JakartaID              NaN      NaN       NaN          NaN
DelhiIN                NaN      NaN       NaN         12.0
MumbaiIN               NaN      NaN       NaN          NaN
ManilaPH               6.0      NaN       NaN          NaN
ShanghaiCN             6.0      NaN       NaN          NaN
São PauloBR            NaN      NaN       NaN          NaN
SeoulKR                NaN      NaN       NaN          NaN
Mexico CityMX          NaN      NaN       NaN          NaN
GuangzhouCN            NaN      8.0       NaN          NaN
BeijingCN             10.0      NaN       NaN          NaN
CairoEG                NaN      NaN       NaN          8.0
KolkātaIN              NaN      NaN       NaN          NaN
MoscowRU               NaN      NaN       NaN          6.0
BangkokTH              NaN      6.0       NaN          NaN
Buenos AiresAR         NaN      NaN       NaN          NaN
ShenzhenCN             NaN     12.0       NaN          NaN
DhakaBD                NaN      NaN       NaN          NaN
LondonGB               NaN      NaN       NaN          NaN
London_stGB            NaN      NaN       NaN          NaN

In [32]:
#parte messa solo perchè l'utima riga sopra non mi va 
graph = graph.where((graph > 1), 0) 

graph = graph.T # dataframe (la trasposta è per mettere i pesi sulle righe o sulle colonne)

In [33]:
## se vogliamo altri formati
gr_array = np.array(graph) ## array

In [ ]:
## networkX prende sia numpy arrays, che liste, che dataframe

In [34]:
## list
gr_ls = gr_array.tolist()
print(gr_ls)

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 6.0, 0.0], [0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 12.0, 0.0, 0.0, 8.0, 0.0, 0.0], [0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0], [12.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0], [6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 12.0, 0.0], [0.0, 0.0, 0.0, 0.0, 12.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0], [12.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 6.0, 0.0, 0.0], [0.0, 0.0, 8.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0], [0.0, 0.0, 0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0], [0.0, 0.0, 0.0, 0.0, 6.0, 6.0, 0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 6.0, 0.0, 12.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [35]:
type(gr_ls)

list

In [36]:
## un tentativo con networkX (mi prende il peso minore però----)

import networkx as nx

In [37]:
G = nx.to_networkx_graph(gr_array)

In [38]:
G = G.to_directed()

In [39]:
G.edges(data=True)

OutEdgeDataView([(0, 8, {'weight': 8.0}), (0, 15, {'weight': 12.0}), (0, 18, {'weight': 6.0}), (0, 4, {'weight': 12.0}), (0, 5, {'weight': 8.0}), (0, 7, {'weight': 6.0}), (0, 10, {'weight': 12.0}), (1, 4, {'weight': 6.0}), (1, 9, {'weight': 12.0}), (1, 16, {'weight': 8.0}), (2, 12, {'weight': 4.0}), (2, 14, {'weight': 12.0}), (2, 17, {'weight': 8.0}), (2, 3, {'weight': 4.0}), (2, 13, {'weight': 8.0}), (2, 19, {'weight': 12.0}), (3, 2, {'weight': 4.0}), (3, 12, {'weight': 6.0}), (3, 17, {'weight': 12.0}), (3, 11, {'weight': 12.0}), (3, 13, {'weight': 12.0}), (4, 1, {'weight': 6.0}), (4, 0, {'weight': 12.0}), (4, 5, {'weight': 6.0}), (4, 7, {'weight': 8.0}), (4, 9, {'weight': 12.0}), (4, 14, {'weight': 12.0}), (4, 16, {'weight': 6.0}), (5, 4, {'weight': 6.0}), (5, 0, {'weight': 8.0}), (5, 7, {'weight': 6.0}), (5, 18, {'weight': 12.0}), (5, 9, {'weight': 6.0}), (5, 10, {'weight': 6.0}), (5, 16, {'weight': 6.0}), (6, 18, {'weight': 6.0}), (6, 8, {'weight': 8.0}), (6, 15, {'weight': 6.0}), (7, 4, {'weight': 8.0}), (7, 5, {'weight': 6.0}), (7, 0, {'weight': 6.0}), (7, 8, {'weight': 12.0}), (7, 18, {'weight': 8.0}), (7, 10, {'weight': 6.0}), (8, 0, {'weight': 8.0}), (8, 7, {'weight': 12.0}), (8, 6, {'weight': 8.0}), (8, 15, {'weight': 6.0}), (8, 18, {'weight': 12.0}), (9, 1, {'weight': 12.0}), (9, 4, {'weight': 12.0}), (9, 5, {'weight': 6.0}), (9, 16, {'weight': 4.0}), (9, 12, {'weight': 12.0}), (9, 14, {'weight': 6.0}), (9, 17, {'weight': 8.0}), (10, 0, {'weight': 12.0}), (10, 5, {'weight': 6.0}), (10, 7, {'weight': 6.0}), (10, 16, {'weight': 10.0}), (11, 3, {'weight': 12.0}), (11, 13, {'weight': 6.0}), (11, 18, {'weight': 8.0}), (11, 19, {'weight': 8.0}), (12, 2, {'weight': 4.0}), (12, 3, {'weight': 6.0}), (12, 9, {'weight': 12.0}), (12, 14, {'weight': 8.0}), (12, 17, {'weight': 6.0}), (13, 11, {'weight': 6.0}), (13, 2, {'weight': 8.0}), (13, 3, {'weight': 12.0}), (13, 18, {'weight': 6.0}), (13, 19, {'weight': 6.0}), (14, 2, {'weight': 12.0}), (14, 12, {'weight': 8.0}), (14, 4, {'weight': 12.0}), (14, 9, {'weight': 6.0}), (14, 16, {'weight': 8.0}), (14, 17, {'weight': 6.0}), (15, 0, {'weight': 12.0}), (15, 8, {'weight': 6.0}), (15, 6, {'weight': 6.0}), (15, 18, {'weight': 8.0}), (16, 1, {'weight': 8.0}), (16, 9, {'weight': 4.0}), (16, 14, {'weight': 8.0}), (16, 4, {'weight': 6.0}), (16, 5, {'weight': 6.0}), (16, 10, {'weight': 10.0}), (16, 17, {'weight': 12.0}), (17, 2, {'weight': 8.0}), (17, 3, {'weight': 12.0}), (17, 12, {'weight': 6.0}), (17, 9, {'weight': 8.0}), (17, 14, {'weight': 6.0}), (17, 16, {'weight': 12.0}), (18, 0, {'weight': 6.0}), (18, 5, {'weight': 12.0}), (18, 6, {'weight': 6.0}), (18, 7, {'weight': 8.0}), (18, 8, {'weight': 12.0}), (18, 11, {'weight': 8.0}), (18, 13, {'weight': 6.0}), (18, 15, {'weight': 8.0}), (19, 2, {'weight': 12.0}), (19, 11, {'weight': 8.0}), (19, 13, {'weight': 6.0})])

In [40]:
GR = nx.from_numpy_array(gr_array)
GR.edges(data=True)

EdgeDataView([(0, 8, {'weight': 8.0}), (0, 15, {'weight': 12.0}), (0, 18, {'weight': 6.0}), (0, 4, {'weight': 12.0}), (0, 5, {'weight': 8.0}), (0, 7, {'weight': 6.0}), (0, 10, {'weight': 12.0}), (1, 4, {'weight': 6.0}), (1, 9, {'weight': 12.0}), (1, 16, {'weight': 8.0}), (2, 12, {'weight': 4.0}), (2, 14, {'weight': 12.0}), (2, 17, {'weight': 8.0}), (2, 3, {'weight': 4.0}), (2, 13, {'weight': 8.0}), (2, 19, {'weight': 12.0}), (3, 12, {'weight': 6.0}), (3, 17, {'weight': 12.0}), (3, 11, {'weight': 12.0}), (3, 13, {'weight': 12.0}), (4, 5, {'weight': 6.0}), (4, 7, {'weight': 8.0}), (4, 9, {'weight': 12.0}), (4, 14, {'weight': 12.0}), (4, 16, {'weight': 6.0}), (5, 7, {'weight': 6.0}), (5, 18, {'weight': 12.0}), (5, 9, {'weight': 6.0}), (5, 10, {'weight': 6.0}), (5, 16, {'weight': 6.0}), (6, 18, {'weight': 6.0}), (6, 8, {'weight': 8.0}), (6, 15, {'weight': 6.0}), (7, 8, {'weight': 12.0}), (7, 18, {'weight': 8.0}), (7, 10, {'weight': 6.0}), (8, 15, {'weight': 6.0}), (8, 18, {'weight': 12.0}), (9, 16, {'weight': 4.0}), (9, 12, {'weight': 12.0}), (9, 14, {'weight': 6.0}), (9, 17, {'weight': 8.0}), (10, 16, {'weight': 10.0}), (11, 13, {'weight': 6.0}), (11, 18, {'weight': 8.0}), (11, 19, {'weight': 8.0}), (12, 14, {'weight': 8.0}), (12, 17, {'weight': 6.0}), (13, 18, {'weight': 6.0}), (13, 19, {'weight': 6.0}), (14, 16, {'weight': 8.0}), (14, 17, {'weight': 6.0}), (15, 18, {'weight': 8.0}), (16, 17, {'weight': 12.0})])

In [41]:
G.nodes()

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19))

In [42]:
length, path = nx.single_source_dijkstra(GR, 19, 18)
print(length, path)

12.0 [19, 13, 18]

In [ ]:
print(GR.edges)